### ISSUE TITLE
Packaging simulator for Project 1

### ISSUE THREAD

**Issue by enqiilim** [nus-cs2030/2021-s1#110]
Can I ask what do they mean by "All classes dealing with the simulation should now reside in the cs2030.simulator package, with only the Main class importing the necessary classes from the package." Does it mean that I can only import packages using Main.java and all my other classes have to import from packages in Main.java? Sorry I don't really know how packaging works >.<

**Comment by zimmmz** [comment]
Hi, erm I think you just need to have package cs2030.simulator in all the class files you created, then in the Main class you just import all of them one by one since prof don't want us to import using cs2030.simulator.*  Eg in your main class you import cs2030.simulator.Event then in you Event class you just add a package cs2030.simulator at the top of the file? As in a way Main is not part of the package it is just using the package so you just import them into your Main class.  Sorry if i didn't ans your qns. :)

**Comment by adelineT-jy** [comment]
If you are asking about having to import all the other classes in the package, then there will not be a need to. If your other class is already in the package itself, you will be able to use them directly (like in labs).

**Comment by marcuspeh** [comment]
Basically all your files other than Main.java need to be in the package (ie have "package cs2030.simulator;" on top of the class). Only java files in the same package dont need to be imported. So, since your Main.java is not in the package, you need to import it in with "import cs2030.simulator.*" and replace the * with the filr you are importing

**Comment by enqiilim** [comment]
@marcuspeh so let's say i have 10 files, i will just repeat import cs2030.simulator.<filename> 10 times in main.java, 1 per file?

**Comment by domlimm** [comment]
Hi @enqiilim , check [this](https://github.com/nus-cs2030/2021-s1/issues/95#issuecomment-699248171) out!

Yup, as per what @marcuspeh has said, repeat all these below, in your `Main.java`. Your `Main.java` should not contain `package cs2030.simulator;`
```java
import cs2030.simulator.Customer;
import cs2030.simulator.Server;
import cs2030.simulator.Event;
import cs2030.simulator.ArriveEvent;
import cs2030.simulator.ServeEvent;
import cs2030.simulator.WaitEvent;
import cs2030.simulator.DoneEvent;
import cs2030.simulator.LeaveEvent;
...
import cs2030.simulator.[FILE_NAME];
```

**Comment by enqiilim** [comment]
okay i understand now, thank you!
