### ISSUE TITLE
Error: cannot find symbol (but it's there...)

### ISSUE THREAD

**Issue by tanruiquan** [nus-cs2030/2021-s1#113]
# Description 
I am very certain that the classes are there.
Plus, the code pass CodeCrunch but jshell keeps giving me this error, any idea why? 

## Screenshots: 
<img width="460" alt="Screenshot 2020-09-29 at 9 31 06 PM" src="https://user-images.githubusercontent.com/70829067/94564971-31958100-029b-11eb-902c-9bca28b7c6e2.png">

**Comment by marcuspeh** [comment]
Try /list to see if it is opened. Maybe its because you forgot to open the parent class

**Comment by tlylt** [comment]
You probably forgot to include SimulationParameters.java as a dependent file. I feel you, was puzzled.

**Comment by wei2912** [comment]
What was the command you used to run `jshell`? You may need to provide all the relevant `.java` files that your code depends on in order to have your classes initialized properly. For me, I fixed this by running

    jshell -q SimulationParameters.java Virus.java BetaCoronavirus.java AlphaCoronavirus.java SARS_CoV_2.java < test1.jsh

EDIT: IIRC `jshell` should display a warning if this happens, but I was unable to replicate that.

**Comment by tanruiquan** [comment]
> You probably forgot to include SimulationParameters.java as a dependent file. I feel you, was puzzled.

Hey, thanks man I forget to include the SimullationParameters.java!

**Comment by tanruiquan** [comment]
Also, i'm a little curious as to why the error points to new AlphaCoronavirus/SARS_CoV_2 part as opposed to simulationParameters part?

**Comment by tjoewel** [comment]
I also had this problem and I actually looked at this for help! But I think the reason why the error points to new AlphaCoronavirus is because jshell is compiling all the files that we pass into it from the command, but when it reaches AlphaCoronavirus, it sees that there is a SimulationParameters.(something), and because we didn't open SimulationParameters.java it cannot find the symbol, and hence does not finish compiling AlphaCoronavirus.java, hence when we do new AlphaCoronavirus it also cannot find the symbol and raises that error.

Im not too sure about this though, please correct me if I am wrong. Thanks!

**Comment by ghost** [comment]
tjoewel should be right. I also encountered this problem as well. Basically if your program extends or implements SimulationParameters.java, then there's a chance it might compile properly but become a runtime error instead. Anyway this should be a .jsh related error and not your coding error and hence shouldn't fail on codeCrunch (I hope)!
