### ISSUE TITLE
Random decimal places for project1 level 4

### ISSUE THREAD

**Issue by Jcheez** [nus-cs2030/2021-s1#119]
![photo_2020-09-27_18-08-55](https://user-images.githubusercontent.com/65590028/94638306-3fcfb580-030c-11eb-893f-20a185ee04aa.jpg)
hi guys, just wondering, how come when i print out the eventStartTimes of my events in my comparator, why isit that some values randomly have many decimal places (for example, 3.0999999999 and 3.1). Shouldn't the input by the user be fixed?

**Comment by wei2912** [comment]
This is due to [floating point error](https://en.m.wikipedia.org/wiki/Floating-point_error_mitigation) as some decimal numbers cannot be expressed exactly in binary (and also due to limited precision in some other cases). Thankfully the error is consistent (i.e. 3.10 will always be represented the same way) so you don't have to perform any rounding before checking for equality.

EDIT: Also, see https://floating-point-gui.de/ for more details about how to deal with floating point error.

**Comment by zzkzzzz** [comment]
hi, Prof Terence explained this question before. You can refer to this #82.

**Comment by ramapriyan912001** [comment]
The floating point error is a common issue across almost all languages.
Use an error threshold like 0.0005 if you wish to test for equality or something of the like.
If you wish to return a quantity, format to 3 decimal places perhaps.

Hope this helps!
