### ISSUE TITLE
Recitation 5 Question 3

### ISSUE THREAD

**Issue by jiehuixx** [nus-cs2030/2021-s1#129]
# Description 
Hi, I was wondering what is the purpose of the **throws** Exception? From the lecture notes, it is said that **throws** is used in the method header to throw the exception out from the method. Hence, in this case, won't we be throwing the thrown Exception out from f() and as such, System.out.print("3") will proceed? However, that doesn't seem to be the case. Please help clarify thanks!
## Screenshots (if any): 
Insert Images here if necessary

**Comment by waynetee** [comment]
Hi @jiehuixx 
The throws keyword is used to *declare* checked exceptions.
In a way, they are there so that your code compiles, not to modify the behaviour of your code.

When an exception is thrown by a line of code, execution halts and the exception is thrown "upwards" until it is "caught", then the code in the catch block is executed.

If there is a finally block, it will be executed before the exception (if not already caught) is thrown up.

**Comment by jiehuixx** [comment]
Oh rightt, thanks for clarifying!
