### ISSUE TITLE
Lab 5 Level 3

### ISSUE THREAD

**Issue by chuashiqi** [nus-cs2030/2021-s1#166]
# Description 
Hi, when doing level 3 I keep encountering this error: Unchecked call to put(V) as the member of the raw type Student. I'm not too sure where I went wrong though because I have put a parameterised type at every part I can think of. Can anybody help :')

## Topic: 
Generics

## Screenshots 
![image](https://user-images.githubusercontent.com/70755428/95593375-2ea94600-0a7c-11eb-8db6-5bdc27d20003.png)
![image](https://user-images.githubusercontent.com/70755428/95593538-6a441000-0a7c-11eb-881b-935922c8f4f8.png)
![image](https://user-images.githubusercontent.com/70755428/95593416-3f59bc00-0a7c-11eb-923c-2f24952fadbd.png)

**Comment by wei2912** [comment]
The `Student` class should be declared as a non-generic class that extends `KeyableMap<Module>`, rather than a generic class. Also, I'm don't think you can downcast `KeyableMap<Module>` to `Student` directly (see https://stackoverflow.com/questions/380813/downcasting-in-java for more details). It should be sufficient to call `super(...)` and then return `this`.

**Comment by chuashiqi** [comment]
@wei2912 got it! tyvm!

**Comment by yuanxin1997** [comment]
Hi, sorry to post at this thread. May I know what to extend in the Module class?
