### ISSUE TITLE
Lab 7 Level 2

### ISSUE THREAD

**Issue by chuashiqi** [nus-cs2030/2021-s1#223]
# Description 
Hi, for level 2 I was having the issue of `"substring"` being returned when `map `was called, as seen here: 
![photo_2020-10-24_01-16-50](https://user-images.githubusercontent.com/70755428/97033959-b8860280-1596-11eb-8f0f-a9893032fcd7.jpg)

This code was my implementation for `map`:
![image](https://user-images.githubusercontent.com/70755428/97033999-cb98d280-1596-11eb-9aee-a3a6a04570a0.png)

but then when I changed my implementation for `map `to this, I no longer have the problem:
![image](https://user-images.githubusercontent.com/70755428/97034058-e23f2980-1596-11eb-9c4c-8ada75cf5fa9.png)

Why is it that my first implementation of `map `did not work? I thought that since there was an `of `method which takes in a value, my first implementation would work and I would not need to pass in a `Supplier`?

**Comment by lkldev** [comment]
Hi, recall that you have two `of()` methods, one takes in `T` and the other takes in `Supplier`. In your first implementation for `map`, the expression `f.apply(this.get())` returns a `U` object. Since there is nothing stopping this expression from running, it is thus invoked (which result in "substring" being printed) and the return value is then passed into the `of` method, invoking `of(T v)`. However, in your second implementation, the expression is being delayed by the `Supplier` (i.e. expression not triggered, nothing is printed), hence `of(Supplier s)` is triggered instead.

**Comment by chuashiqi** [comment]
got it, thanks!
