### ISSUE TITLE
Rec 8 Qn 3 Benefits of Using LazyList

### ISSUE THREAD

**Issue by Chen-Yiyang** [nus-cs2030/2021-s1#225]
# Description 
In the Recitation 8 Qn 3 about the cryptarithmetic problem, the Prof mentioned that the benefits of using a LazyList permutation include:
1. avoiding 6-deep nested for-loops
2. ability to stop the permutation once the solution is found

However, I wonder both of the benefits can be achieved by using a normal recursive Depth First Search function that checks permutations as well without LazyList, then what is the purpose of using LazyList?

**Comment by wei2912** [comment]
I think the main benefit of generating permutations with `LazyList` comes from the terseness and ease of verifying correctness due to the use of functional programming techniques. You could definitely write other algorithms that are much more efficient, but if you don't need the performance benefit then correctness should be prioritised instead (especially since we're dealing with a very small number of permutations, 6! = 720, and any performance benefits are likely to be negligible).

EDIT: Also, development time is another benefit.

**Comment by Chen-Yiyang** [comment]
Thank you for the clarification. I think Function Programming is indeed something that works well with LazyList implementation for the cryptarithmatic problem here.
