### ISSUE TITLE
Lab7 level 2 signature 

### ISSUE THREAD

**Issue by colintkn** [nus-cs2030/2021-s1#235]
```
    <R> Lazy<?> map(Function<? super T, ? extends R> f) {
        if (not computed yet) {
            return Lazy.of(this.supplier);
        } else {
            return Lazy.of(() -> f.apply(this.get())); 
        }
    }
```
I'm having issues with the generics here. What is the return type of the Lazy object? 
My Lazy.of returns a Lazy object of type T. So do I have to create another internal constructor of type R? 
I used the <?> but it gives problems in the test cases. 

Any suggestions for a better way of doing this?

**Comment by domlimm** [comment]
Hi, the return type of map for your case should be `Lazy<R>` as `Function<? super T, ? extends R> f` returns R data type.

Nope, you don't have to create another constructor of type R!

**Comment by srj31** [comment]
Is the if condition necessary, isn't f supposed to map the current value of the Lazy to another value?

**Comment by cnlinh** [comment]
For the if part, my TA says it is not necessary as the caching should already be done in the get() method

**Comment by Maurice2n97** [comment]
the type should be Lazy\<R\> I think.

**Comment by tien87chun** [comment]
@colintkn `Lazy<R> `can store `Lazy<subclass of R>`. Since your function f returns type `? extends R`, returning `Lazy<R>` is sufficient. Also, you should refrain from using a wildcard in your return type. Found an easy to read and simple explanation here! https://stackoverflow.com/questions/22815023/generic-wildcard-types-should-not-be-used-in-return-parameters

**Comment by colintkn** [comment]
Ok thank you all.
