### ISSUE TITLE
Lab 5 Issues

### ISSUE THREAD

**Issue by enqiilim** [nus-cs2030/2021-s1#237]
Not sure why when I test level 6 the starting seem fine but then the query just continues before ending with an no such element exception error (i only copy pasted part of the output)
B
C
A+
A+
A
No such record: Jason CS1010 Lab1
No such record: Jack CS2040 Lab5
No such record: Joel CS2040 Lab312
B
No such record: B Jack CS2040
No such record: Lab6 C Jane
No such record: CS1010 Lab1 A
A+
No such record: A+ Janice CS2040
No such record: Lab1 A+ Janice
No such record: CS2040 Lab4 A+
A+
No such record: A+ Jim CS2010
No such record: Lab1 C Jim
No such record: CS2010 Lab2 B
A+
No such record: A+ Joel CS2030
No such record: Lab3 C Joel
No such record: CS2030 Midterm A
B
C
A+
A+
A
No such record: Jason CS1010 Lab1
No such record: Jack CS2040 Lab5
No such record: Joel CS2040 Lab312
B
No such record: B Jack CS2040
No such record: Lab6 C Jane
No such record: CS1010 Lab1 A
A+
No such record: A+ Janice CS2040
No such record: Lab1 A+ Janice
No such record: CS2040 Lab4 A+
A+
No such record: A+ Jim CS2010
No such record: Lab1 C Jim
No such record: CS2010 Lab2 B
A+
No such record: A+ Joel CS2030
No such record: Lab3 C Joel
No such record: CS2030 Midterm A
B
C
A+
A+
A
No such record: Jason CS1010 Lab1
No such record: Jack CS2040 Lab5
No such record: Joel CS2040 Lab312
B
No such record: B Jack CS2040
No such record: Lab6 C Jane
No such record: CS1010 Lab1 A
A+
No such record: A+ Janice CS2040
No such record: Lab1 A+ Janice
No such record: CS2040 Lab4 A+
A+
No such record: A+ Jim CS2010
No such record: Lab1 C Jim
No such record: CS2010 Lab2 B

**Comment by yusufaine** [comment]
Seems like you're looking up the roster more than the necessary amount of times, and it might be with how you search for the grades.

**Comment by charoi** [comment]
Hi @enqiilim , 
B
C
A+
A+
A
No such record: Jason CS1010 Lab1
No such record: Jack CS2040 Lab5
No such record: Joel CS2040 Lab312
B
^^ above is your code

Looking at your top few outputs, they seem to match except the second last line below in which it gives 3**12**. 
Maybe your toString has issues? Is it looping or iterating too many times? 
The 12 would be the input 12 from test 6, which should not even appear... so your scanner could also be taking in the first line of input wrongly.

**Comment by charoi** [comment]
Its abit hard to determine without your main class, and everyone's implementation is different so can consider running your code on codecrunch to see if any of your previous levels failed the hidden testcases.

**Comment by weiyifei-evelyn** [comment]
The Main class is consisted of mainly three parts. The scanner takes in the integer at the first line, being the number of items to be stored in the HashMap. The second part is to store the assessments under particular module and student. Then, the last part is to take in queries and search in the HashMap.

The first problem in your result is the incorrect output of "No such record: Joel CS2040 Lab312". 12 here is the integer I mentioned in the first part. Please check whether you handle this integer correctly. My recommendation is to use a for loop with this integer as a limit of the number of looping.

Since the first few lines of your result are correct, I assume that the part of storing assessments into the HashMap in your Main class i.e. the second part is right. I think the problem can be due to the third part of the loop, when you use scanner to take in queries. You may consider using sc.hasNext() to determine whether there are any more queries to be handled. If you hand the last two parts correctly and your previous levels are problem-free, you result should be fine.Otherwise, please check your previous levels and see whether there is something wrong.
