### ISSUE TITLE
Lab 6 Level 3

### ISSUE THREAD

**Issue by hhhhanz** [nus-cs2030/2021-s1#253]
Hi, does anyone know how to avoid the following 2 error messagesfor the equals() method?
For the second error, I know I can override the hashCode method to circumvent this but I think this problem can be solved by changing my design for the equals() method itself.

![image](https://user-images.githubusercontent.com/70444061/97797406-bcc9b400-1c57-11eb-842f-e9e4c8fefa7e.png)

Any help would be appreciated! Thank you :)

**Comment by zimmmz** [comment]
Helloo. Maybe you can try casting it using wildcards instead to resolve the unchecked warning issues? Eg like : `LoggerImpl<?> l = (LoggerImpl<?>) o;` hope it helps :)

**Comment by tien87chun** [comment]
^ You should be using a wildcard to type cast the object. Since you do not know what is contained within the `Object`, which is instance of `LoggerImpl`, it could be anything from an Integer, String, Double and so on. Hence you cannot type cast it directly into a `T`. That's why java is telling you that it is an unchecked cast. Hope this clarifies!

**Comment by hhhhanz** [comment]
@tien87chun @zimmmz got it! Thanks so much :)
