### ISSUE TITLE
Regarding wildcard and generics behind equals() method

### ISSUE THREAD

**Issue by dljw98** [nus-cs2030/2021-s1#256]
Just wondering, why does @Override equals(Object obj) only work when I typecast it as Lazy? ?
i.e. in the part where I do Lazy? lazyCopy = (Lazy?) lazy
What's wrong with typecasting using (T) instead if i declared T in the method signature, since <T> is like an unbound type just like if I use ? ?

-edit: some of the diamond brackets are glitching out on my screen so they dont appear in the question - apologies if it appears hard to understand

**Comment by limeugene** [comment]
Hi, if I recall correctly, you need to typecast it as Lazy<?> class after checking that the object passed is indeed a Lazy object. 

This is because the compiler cannot guarantee that the Object you pass into the argument is a Lazy class of Type T. I suppose you'll have an if statement that checks that the object is of class Lazy, and by doing so, you have only checked that the object is of type Lazy. It might not be of type T, so you need to cast the object as Lazy<?>, for type-safety. Hope this helps! :)

Something like this!
![image](https://user-images.githubusercontent.com/4206908/97807129-063af300-1c9a-11eb-8673-9a7b45cfd2fa.png)
