### ISSUE TITLE
Lab 6 Level 4

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#257]
I keep getting this casting error even though the outputs are correct. I'm not sure why it is wrong.

![image](https://user-images.githubusercontent.com/66832279/97807309-0b4c7200-1c9b-11eb-9c22-72eeb38cbe26.png)

flatMap method:
`public <U> Logger<U> flatMap(Function<? super T, ? extends Logger<? extends U>> func) {`
`Logger<U> logger = (Logger<U>) func.apply(this.getValue());`
`.. `
`return logger`
`}`

**Comment by merylseow** [comment]
Your function should be returning a logger of type `Logger<? extends U>` instead of `Logger<U>`.
Try `Logger<? extends U> logger = func.apply(this.getValue())` instead.

**Comment by xingaporean** [comment]
need return Logger<? extends U>

an additional note, actually don't really need to super, iirc lecture say supering is just being generous

**Comment by roopaniedu** [comment]
so that means that my method signature should be
`public <U> Logger<? extends U> ... { ` ?

if I were to do the above, i then get alot more errors :/
![image](https://user-images.githubusercontent.com/66832279/97808644-10152400-1ca3-11eb-88db-0dbebc584769.png)

**Comment by kohkenneth** [comment]
For me instead of creating a new Logger<U> i created a new instance of LoggerImpl<? extends U>. I'm not really sure about the method you are implementing but maybe can try this out!

**Comment by xingaporean** [comment]
nono, u had d original problem bcos d compiler at compile time will erase away ur U and just check if func.apply... is a Logger type
so the compiler will complain because you cannot ensure type safety bcos u casting to a bounded wildcard

d way to resolve is to make sure d assignment type is a unbounded wildcard by ? extends U

which is what merylseow is saying

**Comment by merylseow** [comment]
Yeah the return type of the **function** is `Logger<? extends U>` but the return type of the **method** should still be `Logger<U>`. I get where your confusion is coming from though, so what I can suggest is that instead of returning your current `logger`, you create a new instance of `LoggerImpl<U>` that will take in `logger`'s input and log into the constructor. Then don't have to trouble yourself with all the typecasting.

**Comment by hhhhanz** [comment]
My TA said that in general, we should never use wildcards in the return type so maybe moving forward can use this fact as a hint that the return type shouldn't be  `Logger<? extends U>`

**Comment by kaiyang96** [comment]
I use wildcards in my return types for the labs such as `Logger<? extends U>` but you must remember that when doing anything else to whatever you got from that method, you're dealing with an instance of `Logger<? extends U>` and no longer `Logger<U>`. 

However, from recent labs, there have been some cases I was able to get away without using wildcards in my generics, if that helps anyone from achieving that A.

**Comment by tien87chun** [comment]
> My TA said that in general, we should never use wildcards in the return type so maybe moving forward can use this fact as a hint that the return type shouldn't be `Logger<? extends U>`

^yup, attached an explanation here which may help!
https://stackoverflow.com/questions/22815023/generic-wildcard-types-should-not-be-used-in-return-parameters#:~:text=You%20would%20often%20find%20yourself,return%20type%20of%20your%20method.&text=this%20method%20can%20return%20any,You%20shouldn't%20do%20that.
