### ISSUE TITLE
flatMap codecrunch error "ouch" for lab7

### ISSUE THREAD

**Issue by limeugene** [nus-cs2030/2021-s1#258]
Hi, for lab7 regarding eager vs lazy evaluation, I can't seem to figure out why the first syntax does not work while the second syntax does: 

1. 
V v = f.apply(this.get()).get();
return new Lazy<>(() -> V);

2. return new Lazy<>(() -> f.apply(this.get()).get());

I was under the impression that not returning the variable v means that it won't be eagerly evaluated? Please help me clarify this if I am mistaken. Thanks!

**Comment by dljw98** [comment]
Hi, as you can see in the test cases on CodeCrunch, "ouch!!" is printed as a side effect - this occurs when you assign a variable to the get() value as the "ouch!!" is printed regardless of whether or not you return this assigned variable or put the variable in a supplier later on in the code. In a sense, assigning a variable by evaluating get() before putting it in a supplier is a form of eager evaluation (since the evaluation is done "immediately" in a sense), which the "ouch!!" output is likely trying to get you to avoid doing.

**Comment by xingaporean** [comment]
by doing the assingment statement you would've evaluated alr, means eager liao

**Comment by limeugene** [comment]
@dljw98 @xing221 I see where I went wrong now... thanks all for your input:)
