### ISSUE TITLE
Lab 7 Level 6 IndexOf

### ISSUE THREAD

**Issue by eman-kom** [nus-cs2030/2021-s1#269]
Why does the function run 6 times instead of 5?
![data](https://user-images.githubusercontent.com/29501521/98077197-b8e1a000-1eaa-11eb-922e-0b05f952d469.PNG)

Is my stop condition wrong?
![Capture](https://user-images.githubusercontent.com/29501521/98077293-e595b780-1eaa-11eb-9d3f-10026e14a8f3.PNG)

**Comment by lkldev** [comment]
I am guessing because of the `.takeWhile(Predicate)` method. It will need to validate if the next number return true or false for the `Predicate`, thus it runs `x.get()` which thaws the next value in order to compare. Running `x.get()` would print the output. It would be better if you use the `.limit(int)` method instead. Hope this helps :)

**Comment by eman-kom** [comment]
trueee. But is it possible to not use limit and instead stop iterating when the 10 element is created?

Edit: I am just curious.

**Comment by lkldev** [comment]
Hmmm, you might want to look at the overloaded `iterate` [method](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#iterate(T,java.util.function.Predicate,java.util.function.UnaryOperator)), which takes in a `Predicate`. This way you would not need to use the `limit` method.

**Comment by eman-kom** [comment]
so i changed to stream iterate method to
`(start, n -> !(n.get().equals(v)) , n -> n.map(this.func))`

and its calling the correct amount of "op called" but its not adding the 10th element to the list
![Capture](https://user-images.githubusercontent.com/29501521/98139514-4353ef00-1eff-11eb-8647-d32e78d42a97.PNG)

**Comment by lkldev** [comment]
Can I clarify this is in your `indexOf` method and not your `generate` method? Cause come to think of it, if we have `x.get()` when creating our streams, it would have eagerly evaluated and not be Lazy anymore. With the use of the `limit` method, we do not invoke the `.get()` method which will allow us to create the LazyList. So to my knowledge, I doubt we will be able to create a LazyList without the use of the `limit` method since invoking `.get()` would have it thawed.

**Comment by eman-kom** [comment]
yea the stream iterate is in the indexOf method

**Comment by lkldev** [comment]
Hmmm may I ask why not use the original list generated from the `generate` method?

Edit: If you are trying something similar to #275, you might want to consider that the `List::indexOf` method uses the `equals` method of the object in the list. From there you will find a simpler solution to your answer.

**Comment by eman-kom** [comment]
yeaaaa i guess i will try that thanks!

**Comment by TarciusW** [comment]
If it helps, do make your LazyList implementation as similar to the EagerList provided! just adapt the various variables to make it lazy. it helps on readability and understanding as well :)
