### ISSUE TITLE
Lab6 Level 5

### ISSUE THREAD

**Issue by ghost** [nus-cs2030/2021-s1#273]
# Description 
Anyone knows how to get the 15 in here? Is this a typo? 10 is divisible by 2, returns 5. 5 is not divisible by 2, returns 3 * 5 + 1 = 16. How do we get 15?

## Topic: 
Lab6

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/61898858/98145014-a183d080-1f05-11eb-8f5b-eae088d6eb81.png)

**Comment by domlimm** [comment]
Hi, there isn't an error. 

```java
int f(int n) {
   if (n == 1) { // base
      return 1;
   } else if (n % 2 == 0) { // 1st
      return f(n / 2);
   } else {
      return f(3 * n + 1); // 2nd
   } 
}
```

Since 5 fails the base case and 1st case, it'll go to the 2nd case.

The operation is as follows: **5** -> 3 * 5 = **15** -> 15 + 1 = **16**.

`3 * 5 = 15` is being removed. I'm guessing it's either in your `map` or `flatMap`, or the way you've done the 2nd case in your method `f`.

Hope it helps!

**Comment by ghost** [comment]
Ahh I see, we just have to split that 1 step into 2 steps. Thank you!

**Comment by domlimm** [comment]
Yes!!! @scottsusanto
