### ISSUE TITLE
Running chromium on WSL

### ISSUE THREAD

**Issue by jeffreytjs** [nus-cs2030/2021-s1#28]
Not sure if this is crucial to the mod but I'm trying to **view the javadocs using chromium** as shown in Video 7-API as shown at timestamp 13:19.

I am using **Windows Subsystem Linux (WSL) Ubuntu 18.04**, not sure what other specifications are required so do prompt me on what else would be need and I'll share them here.

I have tried multiple proposed online solutions as shown below but it still doesn't work.

Failed attempts:
Attempted to use `google-chrome` as shown on [WSL/issues](https://github.com/microsoft/WSL/issues/3778) 
Attempted to use `chromium-browser` through `sudo apt install --assume-yes chromium-browser` as shown on [ubuntu guide](https://www.simplified.guide/ubuntu/install-chromium-browser)

Alternatively, I could cp the files to my local drive then open normally but it's tedious.

**Comment by pchunky** [comment]
I'm not sure why you need to install a separate browser on your WSL when you (most probably) already have a browser on the same Windows system. Even if you can install Chromium on your WSL, then most probably you would need to Xserver to allow WSL's GUIs to appear on Windows. That is even more tedious.

A simpler way I'd prefer is just to open the directory in which your javadocs were generated by invoking `explorer.exe .` and just open the HTML as I'd do in a normal Windows system using my browser.

Hope this helps.

P.S. There is no need for `cp`. WSL and Windows are in the same system and the files are shared and accessible by each other. Just need to use `explorer.exe .` as a link due to different filesystems.

**Comment by rohit0718** [comment]
this may help as well! https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux

**Comment by pchunky** [comment]
Thanks, Rohit. That is a good tip for saving time if one is to open HTMLs from WSL all the time.

And @jeffreytjs, let me also address the case in the video. The video you watched in LumiNUS were prepared by our saviour lord @yonggqiii, and he is using *Arch Linux*. In that system, the browser of his choice is probably Chromium, hence the `chromium index.html` he invoked from the terminal.

However, WSL is quite different from Windows (assuming WSL 1.0), since it is (a simplified explanation) virtual machine running on Windows, so the GUI display is separately handled.

**Comment by jeffreytjs** [comment]
Thank you @purfectliterature and @rohit0718 for the tips, yes `explorer.exe .` works well now. This has helped me understand linux a little better, the lack of need for chromium on WSL could be the reason why there's not much information about it online. 

I'll be closing this issue now.

**Comment by yonggqiii** [comment]
@purfectliterature 's clarification is spot on. Thanks!
