### ISSUE TITLE
peek vs map in Stream

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#282]
In Java API, stream interface has two methods, namely peek and map.

1) peek
peek​(Consumer<? super T> action): Returns a stream consisting of the elements of this stream, additionally performing the provided action on each element as elements are consumed from the resulting stream.

2) map
map​(Function<? super T,​? extends R> mapper): Returns a stream consisting of the results of applying the given function to the elements of this stream.

Both are intermediate operations, and both seem to perform an operation on every elements in a stream. However, they are two different methods as defined in Java API. Could someone help summarise the key difference between them? In which cases, we need to use peek or map? Also, are there any cases where we can use them interchangeably?

**Comment by kohkenneth** [comment]
I think this link might help! https://www.baeldung.com/java-streams-peek-api

**Comment by Octanis0** [comment]
Please refer to the API for [``peek()``](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#peek(java.util.function.Consumer)).

``peek()`` is only meant for debugging purposes, like printing out the ``Stream`` to make sure your generation or operations are done correctly. Some terminal operations like ``count()`` will cause intermediate ``peek()`` operations to be **completely ignored**. In this example, since ``peek()`` doesn't change how many elements will be produced in the end, the program may optimise its execution by removing debugging operations that it knows for sure will not change the result given by the terminal operation.

I think it's better to just stick to ``map()`` when you want to actually change the elements in your stream.

**Comment by xingaporean** [comment]
peek is for debugging only

**Comment by jedlwk** [comment]
To further add on to the following comments, here are some visuals that had helped me with my understanding! Hope it helps you too!

This photo below further clarifies how a map works!

![image](https://user-images.githubusercontent.com/65217862/98328498-d771a380-2030-11eb-9ec3-f3cf0fee8360.png)

This photo shows how the system will read both a map and peek and how you can use it to essentially debug! :)

![image](https://user-images.githubusercontent.com/65217862/98328594-0e47b980-2031-11eb-8662-60ae8e90d7bc.png)

Hope it clarifies! :D

**Comment by weiyifei-evelyn** [comment]
Thank you so much for your clarification!
