### ISSUE TITLE
PE2 test4_1

### ISSUE THREAD

**Issue by chuashiqi** [nus-cs2030/2021-s1#287]
# Description 
Hi, anybody has any idea how to fix this? my sample test cases all work but not sure why I'm getting this error. Thanks!
![image](https://user-images.githubusercontent.com/70755428/98437910-31519680-2121-11eb-832e-09ab292edf9b.png)

**Comment by benluiwj** [comment]
I think your code is ticking when it is not suppose to

**Comment by CWei88** [comment]
When you use your tick function, did you reference to the same list when ticking? It might explain the extra ticks

**Comment by chuashiqi** [comment]
@CWei88 no, i return a new Room everytime i call tick()

**Comment by CWei88** [comment]
@shhiiiqqqqiiiii Yeah but I meant something like for example:
Let's say your tick() returns a new Room like this `new Room(this.name, this.list)`, where list is the things in your room.

Let's say:
`Room a = new Room("a").add(new Troll()).add(new Sword())`
`Room b = a.tick()`

When you get a from this, the objects in the Room should not be ticked in a but ticked in b.

But if you use `this.list`, when you tick in b, the items in a will also be ticked, as they are referencing the same list. I was wondering if that was the case that had resulted in the extra ticks seen in your code since I'm not too sure also but it was something that came to my mind.

**Comment by chuashiqi** [comment]
@CWei88 ah i see what you mean. will test it out. thank you!
