### ISSUE TITLE
PE2 - Program not compilable

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#293]
I tried to submit my Room and Candle java files through codecrunch to check the outputs but codecrunch keeps saying that it is not compilable? However I am actually able to compile both files so I'm confused about this issue

**Comment by Josephaedan** [comment]
If you're talking about the "File not found: main*.java" error, I encountered this problem both PEs. The first one was because one of my java class files was not named correctly ("class.java instead of Class.java). I was unsure what went wrong with my second one, but I renamed everything and reuploaded and it was fine after. Perhaps you should check if any of your files have the wrong name?

**Comment by roopaniedu** [comment]
I did not receive that error. I received the one below. I tried to even just upload a barebone Room.java file that has no way to be uncompilable but i'm getting the same error and I'm so confused

![image](https://user-images.githubusercontent.com/66832279/98465281-16efe980-2203-11eb-9c11-c5116c5dbf14.png)

**Comment by hhhhanz** [comment]
Is it bc 
![image](https://user-images.githubusercontent.com/70444061/98465636-3b4cc580-2205-11eb-9ddc-d07f82f8291d.png)

**Comment by roopaniedu** [comment]
Yea i checked that. I actually removed my import statements and submitted a barebone Room.java file and yet I'm getting the same error

**Comment by hhhhanz** [comment]
Hmm :( may be better off asking ur TA for help?

**Comment by Josephaedan** [comment]
You should probably raise this issue to your TA as I am unsure if sending files or code to other students is allowed for this PE2 given we should not be collaborating.

**Comment by roopaniedu** [comment]
Alright will do. thanks for the inputs guys!
