### ISSUE TITLE
PE TestCase 4_1 errors

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#302]
I passed the given test case in level 4 but am unable to pass test case 4_1. I can't seem to figure out where the mistakes are either (because codecrunch doesnt show the full output)

![image](https://user-images.githubusercontent.com/66832279/98575808-9c9f9200-22f4-11eb-8344-b227c376e300.png)

![image](https://user-images.githubusercontent.com/66832279/98575911-bf31ab00-22f4-11eb-9238-6b101faf610a.png)

**Comment by jiayi-lim** [comment]
1. Missing Troll states: The problem is likely to be the Troll class, specifically when the Room tick and requires the second onwards state ("Troll is getting hungry", etc) since it seems to not have any error with the first state ("Troll lurks in the shadows."). Maybe you can check the tick method and its helper method in Troll? 

2. killTroll: Make sure to check that both sword and troll is present before killing troll. 
I suspect the problem for the incorrect output is at the very first line your room h (line 37 of your ouput) has a sword when it is not supposed to. Maybe you should check if any parts of your code added a Sword. Just a note, takeSword should not be adding sword to the items in room. takeSword is when you already have a sword in your room and you wanna take it with you. 

Hope this helps!

**Comment by roopaniedu** [comment]
I will check my code again regarding this! Oh, any idea about the output for line 28?

**Comment by jiayi-lim** [comment]
It is weird cos you managed to pass the given test case in level 4! So it should be working fine. But I guess if there is anything wrong, it is either your add method or tick method (and the methods that support tick). Also, Candle class seems to be working fine so maybe you want to check your Troll class against the Candle class since they are quite similar!

**Comment by roopaniedu** [comment]
Thanks so much @jiayi-lim ! Finally able to almost finish the PE :)
