### ISSUE TITLE
Project 2 Level 6 - Cyclic Dependency issue

### ISSUE THREAD

**Issue by rcdl2222** [nus-cs2030/2021-s1#314]
For level 6 of Project 2, I have an issue regarding SelfCheckoutCounter, DoneEvent and ServeEvent.

For SelfCheckoutCounter, if there are customers in the common queue, a ServeEvent will be immediately called in the execute() method of DoneEvent once the server has completed serving the previous Customer. However this creates a cyclic dependency issue where obviously, ServeEvent returns DoneEvent, but now DoneEvent also relies on ServeEvent, which made the CodeCrunch compiler throw an error. 
![image](https://user-images.githubusercontent.com/71259013/98764016-e16f1a00-2415-11eb-8e2a-a919db26ddcd.png)
There was a previous post about cyclic dependency but it didn't really apply to my issue. My code's output is correct for level 6, so the logic behind it (should be) correct. Any help will be appreciated!

**Comment by JedrekLoo** [comment]
Like you said, you cannot call Serve Event in the execution of Done Event because it will create a cyclic dependency. 
You can try having the Done Event only updating the status of the server/counter to being available, and another event which allows the next customer in the queue to check the updated status of the server, which then creates a serve event if the server is available.

**Comment by rcdl2222** [comment]
Solved, thanks for your help @JedrekLoo !
