### ISSUE TITLE
PE2 Test6

### ISSUE THREAD

**Issue by dtse2401** [nus-cs2030/2021-s1#324]
# Description 
Hello, I seem to be having an issue with understanding the sequence in which the items are listed. For the below test case, at no point was `dropSword` called, so when `back()` is called, why is the sword not listed before the candle since it was brought back?

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
Insert Images here if necessary
![test6_1](https://user-images.githubusercontent.com/71458218/98969492-da492880-2549-11eb-9bf1-f18f5a802c60.png)

![test6_2](https://user-images.githubusercontent.com/71458218/98969529-e3d29080-2549-11eb-9e3a-648b30af6acd.png)

**Comment by e0531336** [comment]
I too had the same issue, you just need to ensure that r1 r2 and r3 are not being mutated when you call back() and go(). You may want to try running test 6 up to the first function where back is called on r3.

**Comment by hhhhanz** [comment]
I think its bc things in the room that were created earlier will be listed first. Since the Candle in room 1 was created first, it will be listed before the Sword created in room 3

**Comment by ghost** [comment]
When u go() to a new room and bring a sword, you add the sword to the front of the list.
When u back() to an old room and bring a sword, you add the sword to the back of the list.

**Comment by ErnestCYW** [comment]
Did you manage to solve this issue? I had the same problem :)

I think it's because when you move from room to room, you bring the sword with you. So essentially it's removed from the previous room. When you go back to the previous room you add back in the sword, so it's at the bottom of the list. At least that's how I interpreted the question.

So translating into code would mean that you "back" into the old room by creating a new Room Object with the correct name and the same things as the old room + the sword then the print would be at the bottom. Alternatively, you could do what I did at first and brute force using the set/add based on index command in the List interface :)

Hope this helps :)

**Comment by SkyBlaise99** [comment]
The input is `r3.tick(takeSword).back().tick(killTroll).back()`
so u firstly take the sword and go back to r2 -> (dining, candle, troll, sword)
then u kill the troll -> (dining, candle, sword)
then u back again to r1 -> (foyer, candle, sword)
and remember to tick() r1!

**Comment by dtse2401** [comment]
Thanks for all the help guys! I resolved the issue already. I misunderstood the back() function as taking something back, so I thought that the taken item had to be placed first!
