### ISSUE TITLE
packaging issue

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#346]
![image](https://user-images.githubusercontent.com/51086295/99093251-332dc500-260d-11eb-9cc0-e02588f60fcb.png)

Does anyone knows what is the issue behind this ?
It is working fine on my laptop

**Comment by chuashiqi** [comment]
Main is outside the package and because the constructor of RandomGenerator is not public you can only access use the constructor in the classes that are within the package

**Comment by YuFeng0930** [comment]
Hi,
Since RandomGenerator is a .class file in the package cs2030.simulator, your Main class should import that package to access the RandomGenerator. You can consider packaging all the files first and import the whole package in your Main class.

**Comment by chongweil907** [comment]
![image](https://user-images.githubusercontent.com/51086295/99097249-5313b780-2612-11eb-8824-6778e0254b25.png)
 I did that tho

**Comment by YuFeng0930** [comment]
As the error message suggested, you can only access RandomGenerator inside the package which is cs2030.simulator, so you cannot directly import RandomGenerator in Main class. It also means that RandomGenrator should never appear in your Main class. Try to put the implementation details, like the use of PQ, in a new class which is within cs2030.simulator package so that you can access RandomGenerator within the package.

**Comment by cnlinh** [comment]
You try declaring a new class in cs2030.simulator package that contains RandomGenerator as an attribute. That way, you can access all of its private methods via this new class
