### ISSUE TITLE
PE Level 5

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#348]
Hi, I'm confused about how level 5 the `go()` method works.

Based on this test case, 
<img width="771" alt="Screenshot 2020-11-14 at 8 19 05 AM" src="https://user-images.githubusercontent.com/71199647/99132671-18ca0a80-2652-11eb-85d4-51aa461c017d.png">
It means that the new room entered has a memory of all the things in the previous room, so there is `"Sword is shimmering."` even though there is no `sword` in the new Room.

However, in the test cases below, 
<img width="507" alt="Screenshot 2020-11-14 at 8 21 09 AM" src="https://user-images.githubusercontent.com/71199647/99132746-5f1f6980-2652-11eb-9e52-2f9d07bd30f0.png">
Only the thing existing in r3 is printed i.e. `Troll is getting hungry.` is printed but not `candle` and `sword` in the previous rooms.

I was thinking of copying all the things in the previous room and add the things in the new Room. However, it will fail the second test case mentioned above. Could someone help me interpret why the test cases are like that? And how should I approach this level? 

Thank you very much!

**Comment by hengyiqun** [comment]
I think the items in the previous room are only copied over when you make the following call (e.g. .go(x -> new Room("", x))
new Room("dining").add(new Candle()).add(new Sword()).go(x -> new Room("mystery", x))

but when you call 
new Room("foyer").add(new Sword()).tick(takeSword).go(x -> new Room("dining").add(new Candle())),
the new room you go to will only have what is specified inside go

**Comment by darrenhoon** [comment]
interpretation of test cases:
> It means that the new room entered has a memory of all the things in the previous room, so there is "Sword is shimmering." even though there is no sword in the new Room.
- this is because there's a tick(takeSword) before the .go(...) so the code must have generated a new sword in the next room and removed the sword in the current room, if your implementation is as a Room -> Room. If your implementation was Player -> Room, your Player needs to have the sword in the inventory.

how to approach the level:
1. generate the next room first using the function as passed in by the parameter of the go method
2. loop through your current container in the current room to check for the status of your sword (ie whether it is taken or not). if it is, add it to the next room and remove from the current room. If not, just do nothing to the sword (ie leave it in the current room)
3. depending on your implementation, remember to add this current room to your history/backlog of rooms for the back() method in level 6
4. return the next room

**Comment by hengyiqun** [comment]
For the first case you pointed out, sword exists because you have taken sword along with you into the next room

Hope this helps! :)

**Comment by weiyifei-evelyn** [comment]
> For the first case you pointed out, sword exists because you have taken sword along with you into the next room
> 
> Hope this helps! :)

Ohhh I see, so do you @hengyiqun mean that there should be two types of go() method:
1. .go(x -> new Room("mystery", x)): I just cope everything in the old room and save the things in the new room
2. .go(x -> new Room("dining").add(new Candle())): Only when I takeSword from the old room, I create a new sword in the new room. Then follow what @darrenhoon suggest.

If I'm wrong, please correct me :)

**Comment by darrenhoon** [comment]
@weiyifei-evelyn idt it is possible to create 2 types of go method in this instance because for both cases 1 and 2, they take in the same parameter of a Function / UnaryOperator so we can't have an overloaded go() method

in case 1, the "Copying" is done by the function parameter. that is accounted for in line 1 of the steps provided in my previous post. to elaborate a bit more, the generation of the next room would be just
`Room nextroom = f.apply([this room's list])`

this is because the decision on whether this room's items are the same as the next room's is not done by the go() method. rather, it is the responsibility of the function passed into the go() method.

the go() method's responsibility is just to edit the status of the sword and return the next Room (of which its contents are decided by the function passed into the go() method), not decide it's contents except for the presence/absence of the sword.

**Comment by hengyiqun** [comment]
Yup, but I think it may be needed to incorporate both versions into one single go method.

This is because the method signature and number of parameters are the same for both versions, so it is not possible to have overloaded go methods in this case. If I am not mistaken, the suggestion by @darrenhoon has already incorporated both versions.

**Comment by weiyifei-evelyn** [comment]
> @weiyifei-evelyn idt it is possible to create 2 types of go method in this instance because for both cases 1 and 2, they take in the same parameter of a Function / UnaryOperator so we can't have an overloaded go() method
> 
> in case 1, the "Copying" is done by the function parameter. that is accounted for in line 1 of the steps provided in my previous post. to elaborate a bit more, the generation of the next room would be just
> `Room nextroom = f.apply([this room's list])`
> 
> this is because the decision on whether this room's items are the same as the next room's is not done by the go() method. rather, it is the responsibility of the function passed into the go() method.
> 
> the go() method's responsibility is just to edit the status of the sword and return the next Room (of which its contents are decided by the function passed into the go() method), not decide it's contents except for the presence/absence of the sword.

@darrenhoon Okay, I understand now. Thanks for your detailed clarification! I'll try to follow what you suggest.

**Comment by weiyifei-evelyn** [comment]
> Yup, but I think it may be needed to incorporate both versions into one single go method.
> 
> This is because the method signature and number of parameters are the same for both versions, so it is not possible to have overloaded go methods in this case. If I am not mistaken, the suggestion by @darrenhoon has already incorporated both versions.

Thank you for your prompt response :))
