### ISSUE TITLE
How do I scroll on the Ubuntu terminal when I'm not in vim mode?

### ISSUE THREAD

**Issue by LapisRaider** [nus-cs2030/2021-s1#35]
I'm currently having trouble scrolling through the Ubuntu terminal. I'm trying to run a file and the terminal printed out a list of errors. However, I can't fully see the error list because I don't know how to scroll on the terminal and thus, am having trouble debugging my code. I searched up online telling me to click Ctrl + page up, however, it is not working for me. I also read up there's an option for setting the limit of lines I can scroll, but I cannot find the option anywhere on my terminal.

Does anyone know how I can scroll on the terminal of Ubuntu when I am not in Vim mode?

**Comment by domlimm** [comment]
EDIT 1:
maybe you can check [this](https://github.com/microsoft/terminal/issues/137) out

EDIT 2:
just tried running wsl via start menu. **Win key -> Ubuntu** scrolling works. if i did this instead, **Win key -> cmd -> `wsl`**, it doesn't work...

EDIT 3:
try setting this property to `9001` on your terminal (**Win key -> cmd -> `wsl`**).
![image](https://user-images.githubusercontent.com/46486515/92300799-6b22e700-ef90-11ea-9580-26e942981788.png)


I would love to know too! I tried the methods that you've tried but it didn't work for me... On mac scrolling does work though so that's quite odd... I ended up giving up lol

This is my terminal properties for windows

![image](https://user-images.githubusercontent.com/46486515/92300671-4d08b700-ef8f-11ea-99ac-185aee246924.png)

whats yours?

**Comment by LapisRaider** [comment]
> EDIT 3:
> try setting this property to `9001` on your terminal (**Win key -> cmd -> `wsl`**).
> ![image](https://user-images.githubusercontent.com/46486515/92300799-6b22e700-ef90-11ea-9580-26e942981788.png)


Thank you, setting the height property to a large number works!
