### ISSUE TITLE
PE2 Level3

### ISSUE THREAD

**Issue by elizabethh07** [nus-cs2030/2021-s1#350]
hi this is my error for level3 and i'm not sure how to solve the error.
![image](https://user-images.githubusercontent.com/65172909/99141774-91988900-2689-11eb-8fb9-513b0c46e34a.png)

this is my code:
![image](https://user-images.githubusercontent.com/65172909/99141791-ab39d080-2689-11eb-8615-b6860ad4175d.png)

thanks in advance!

**Comment by domlimm** [comment]
Hi, looking at your code snippet, your `takeSword` returns a List of the Things right?

Try printing out `newX` and see what you get before returning in `takeSword`, run it locally 👍🏻

**Comment by tien87chun** [comment]
I think the issue here is that if your sword is not taken, you create a new sword that is taken and replace it in the list of Things, then the code goes to the next line and sees that the sword you have just taken is taken, then it executes the second line as well. You may want to change the second line to an `else`?

^ and yes I think printing out the newX will definitely help you to debug this

**Comment by patriciafzy** [comment]
I had the same problem as you previously. What I did that work was to change the if-if loop to if-else loop as mentioned by tien87chun and it should work after that!

**Comment by sdas04** [comment]
Hi, I had the same problem too! If you still have the same issue after trying the suggestions above, the problem could be that your sword.hasTaken() returns false again because your tick() resets your sword to Sword(false). This is given that you have a method that takes care of the change of state across all your items (i.e. candle, sword etc).

**Comment by elizabethh07** [comment]
thank you everyone! :)

**Comment by Andrewzhang217** [comment]
@sdas04 Thank you so much. I encountered the same problem as you. I only had a method to change the state of a sword at start, then tick() call this method and set the hasTaken() to a default false,

**Comment by sdas04** [comment]
@Andrewzhang217 no probs!
