### ISSUE TITLE
Project Level 3: Issues using Random Generator Class

### ISSUE THREAD

**Issue by jerimiglo** [nus-cs2030/2021-s1#352]
# Description 
I have placed RandomGenerator.class into my cs2030.simulator directory along with my other classes (as seen on left panel on vscode). However, vscode still doesn't seem to recognise RandomGenerator as an appropriate class . How do i resolve this issue?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/73515067/99144465-1e027600-26a1-11eb-829d-2de4d203b1ac.png)

**Comment by KaushikR1999** [comment]
Hi, correct if I'm wrong, but your EventManager is not in the cs2030.simulator package right? If so, you shouldn't be able to access RandomGenerator from this class itself because RandomGenerator has private methods. So, you should use a wrapper class to access the RandomGenerator from outside the package. You can refer to this post #252 for more details.

**Comment by jerimiglo** [comment]
hi, thanks for the reply! But my EventManager is in the package so I'm not sure why RandomGenerator cannot be accessed.

**Comment by jerimiglo** [comment]
i managed to resolve the issue! thanks!

**Comment by dengxueqi** [comment]
hello! How did you resolve the issue?

**Comment by jerimiglo** [comment]
> hello! How did you resolve the issue?

hey! i don't think vscode recognises the RandomGenerator class because we are only provided the class file! But in the terminal, you can run `javac -d . *.java` followed by `java Main 1 1 5 1.0 1.0 ` for the first test case in level 3 for example! Hope this helps!
