### ISSUE TITLE
Project 2 Level 6 

### ISSUE THREAD

**Issue by eman-kom** [nus-cs2030/2021-s1#374]
Hi, may I know why customer 18 chooses to wait for Server 1 instead of being served by Server 2?

Assuming Server 2 is resting, shouldnt it still allow waiting customers?

![Capture](https://user-images.githubusercontent.com/29501521/99180064-1bb22180-275e-11eb-8c9f-04f4e38bf0a6.PNG)

**Comment by glennljs** [comment]
Because Server 2 is resting which makes both Server 1 and Server 2 in the "cannot serve but can queue" stage. Hence the customer will queue with the first Server which is Server 1.

Edit: Only in the greedy test cases will the greedy customer queue with Server 2 since Server 2 has a shortest queue (0 in Server 2 to 1 in Server 1). This is one of the differences between the last two public test cases.

**Comment by eman-kom** [comment]
ok i got it now

Thanks a lot 👍
