### ISSUE TITLE
Project 2 Level 3 Random Generator Class

### ISSUE THREAD

**Issue by remuskwan** [nus-cs2030/2021-s1#377]
For Project 2 level 3, I have problems accessing the RandomGenerator class in Main.java or other classes within my cs2030.simulator package. Is there something I have to do to convert RandomGenerator.class to a .java file? Thanks in advance!

**Comment by wei2912** [comment]
The `RandomGenerator` class should be placed in `cs2030/simulator/`, and you won't be able to access its methods outside of the `cs2030.simulator` package according to the API at https://www.comp.nus.edu.sg/~cs2030/RandomGenerator/cs2030/simulator/RandomGenerator.html.

If this doesn't resolve the issues you have with accessing the classes in the package, you can try deleting all the `.class` files in `cs2030/simulator/` and rerunning `javac -d . Main.java` in the directory containing `Main.java`. (Make sure that you do not delete `RandomGenerator.class` in the process, since you would have to redownload it...)

**Comment by remuskwan** [comment]
I tried deleting all the `.class` files in `cs2030/simulator/` and reran `javac -d . Main.java` but the issue persists... I'm still having trouble accessing the RandomGenerator within my classes in the package...

**Comment by FergusMok** [comment]
One way to resolve it is wrapping the RandomGenerator inside your own custom RandomGenerator class, and you place this custom class inside the package, which Main can call. 
This was what the person did in #311.

**Comment by joelwongjy** [comment]
Here is what I did that finally worked.

1. Dump all the .java files into one common folder. Make sure all the files have `package cs2030.simulator` except `Main.java`.
2. Navigate to the folder and run `javac -d . *.java`.
3. Terminal will probably tell you that RandomGenerator cannot be found but the .class files would have been created in a `cs2030/simulator/` directory. Go into this folder and dump the `RandomGenerator.class` there.
4. Go back to the folder where all the .java files are sitting in and compile again. There should be no errors.

Take note that RandomGenerator has to be instantiated by a **file inside the package** i.e. anything but Main.java. You can create a `Simulator.java` class and move your `Main.java` code in here, or create a `MyRandomGenerator.java` class and instantiate the `RandomGenerator` there.

**Comment by remuskwan** [comment]
^Thanks! Your method worked for me 👍
