### ISSUE TITLE
Difference between interface and abstract class

### ISSUE THREAD

**Issue by rickyaandrew** [nus-cs2030/2021-s1#38]
# Description 
Hi, i would to ask what is the difference between an interface and an abstract class? why abstract class can implement new methods + write empty methods for sub-classes, while interface can only write empty methods for sub-classes and gives error if we try to implement a new method in it?

## Topic: 
Lecture 3 substitubability in OO design and interfaces

**Comment by ClementNgZiQian** [comment]
https://www.guru99.com/interface-vs-abstract-class-java.html#:~:text=An%20abstract%20class%20permits%20you,class%20can%20implement%20multiple%20interfaces.

I think this website can show you some comparisons between an interface and abstract classes, and which one is better in terms of what.

**Comment by HolmesJJ** [comment]
Although this question has been closed, I still hope to share my views and consolidate my knowledge through this question ^_^

Q: Difference between interface and abstract class?

A: Thanks to @ClementNgZiQian for sharing, I believe the website he shared has explained the difference between interface and abstract class in programming in detail.

However, I think we can't just distinguish between interface and abstract class from programming, **we have to understand their design purpose**.

Engineering knowledge has a very obvious characteristic: **"How to use"**. When discussing the difference between interface and abstract class, I tried to summarize the difference from the perspective of "use", which is the **design purpose**.

1. The design purpose of interfacesand abstract class is different. **Interface is an abstraction of action, and abstract class is an abstraction of root**. 

- For abstract class, such as **Man** and **Woman**, we can design a lower level abstract class for these two classes -- **Human**. 

- For interface, we can sit down to eat, stand up to eat, use chopsticks to eat, use fork to eat, and even use our hands to eat. Then we can abstract these eating **actions** into an interface -- **Eating**.

- So in high-level languages ​​(such as Java, C#), **a class can only inherit one abstract class** (because you can't be both a living thing and a non-living thing). **But a class can implement multiple interfaces at the same time**, such as driving interface, skating interface, swimming interface.

In conclusion, inheritance is a "is-a" relationship, and interface is a "has-a" relationship. If a class inherits an abstract class, the subclass must be the type of abstract class. And the implementation of the interface is the relationship of "has or not". For example, if a person can play Dota, then can implement playDota() interface, if not, then cannot implement playDota() interface.

Q: Why abstract class can implement new methods + write empty methods for sub-classes, while interface can only write empty methods for sub-classes and gives error if we try to implement a new method in it?

A: The subclass must **override** all the **abstract methods** of the superclass. When a subclass implements an interface, it needs to implement all the **methods** in the interface. This is the rule of interface and abstract class.
