### ISSUE TITLE
Project 2 Cyclic Dependency

### ISSUE THREAD

**Issue by kohwenjie** [nus-cs2030/2021-s1#380]
Hi can someone please help me understand whats going wrong here. It seems that after adding the self checkout counters i have somehow introduced cyclic dependency between so many classes. shouldnt ArriveEvent be able to call on ServeEvent, WaitEvent, LeaveEvent etc? if so why am i experiencing this?

![image](https://user-images.githubusercontent.com/70895902/99187907-4cad4900-2794-11eb-8387-907f46260443.png)
![image](https://user-images.githubusercontent.com/70895902/99187913-58007480-2794-11eb-9a7b-b782b7ccb88c.png)

**Comment by FergusMok** [comment]
Seeing from your output, try to resolve the ServeEvent -> DoneEvent and DoneEvent -> ServeEvent, and continue debugging from there.
Also, you still need some legacy code for your test 2_2. i.e I think your ArriveEvent is missing a constructor ArriveEvent( customer ).

**Comment by merylseow** [comment]
I had the same problem too, where they showed a whole bunch of cyclic dependency errors. But usually it's only like 1 or 2 that has problem (most probably ServeEvent and DoneEvent like mentioned above) then the rest will resolve along with it.

**Comment by kohwenjie** [comment]
@FergusMok for the legacy code, i do have a constructor for ArriveEvent for ArriveEvent(Customer) tho, im not sure why thats coming up. As for the ServeEvent -> DoneEvent and DoneEvent -> ServeEvent, i did it in the way that the Self checkout counters that had customers in the queue after they have finish serving their current customer, in the DoneEvent, if there was still customers in the shared queue, it would call a ServeEvent on the next customer in line. How do you call the next serve event without inducing a cyclic dependency? i tried making an intermediate class but its the same result :(

**Comment by FergusMok** [comment]
@kohwenjie, maybe try changing your implementation. 
An intermediate class would make it DoneEvent-> Intermediate-> ServeEvent. You should try to make the customers in the shared queue (probably ServeEvents) continue with the execution, so that the events flow naturally Serve -> Done -> Nothing. 
Personally, I implemented it as : 
If there are still customers in the shared queue, I changed all the customers' server and time to the self-checkout that is finishing the fastest. Then, I will just take the customer event with the smallest ID number, execute, then immediately check all the self-checkout to see who is finishing the fastest, and change the shared queue ID and time to that server.

**Comment by kohwenjie** [comment]
@FergusMok @merylseow Thanks i finally fixed the problem!
