### ISSUE TITLE
Project 2 Level 3 ( CodeCrunch Scanner error)

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#385]
I have individual classes for all the different events. My randomgenerator is created in my Simulator.java class. My process of adding the serviceTime to the serve event is to do the following within ServeEvent.java:
`eventTime= Simulator.getRandomGenerator().genServiceTime(); + eventTime`;

however, the above case results in  cyclical dependency. Any ideas for adding the additional servicetime to my ServeEvent?

**Comment by CWei88** [comment]
Do you have the error for Cyclic dependency, because I don't seem to see any Cyclic dependency.

For the Service time, I used a Supplier instead of the RandomGenerator class instead. When I need the service time during ServeEvent, I would just use `service Time.get()` to retrieve the service time of the Customer.

**Comment by yusufaine** [comment]
> Do you have the error for Cyclic dependency, because I don't seem to see any Cyclic dependency.
> 
> For the Service time, I used a Supplier instead of the RandomGenerator class instead. When I need the service time during ServeEvent, I would just use `service Time.get()` to retrieve the service time of the Customer.

I ended up doing the same too – made a serviceTime attribute for customer that's a supplier and only getting the value when needed in my ServeEvent.

**Comment by glennljs** [comment]
I believe there are multiple ways to solve this. One common way is passing the randomGenerator.genServiceTime() as a supplier to the Customer so that it is lazily evaluated on serve time. Another method that I personally used was to pass the randomGenerator into my Shop and simply call genServiceTime() each time I was serving a Customer. 

Hope this helps!

**Comment by roopaniedu** [comment]
Hey guys, i managed to solve that issue by implementing the supplier function. Its seems to be working on the given testcases. But when I try to upload to code crunch, i get the following error:

![image](https://user-images.githubusercontent.com/66832279/99233737-9a768f80-282e-11eb-8912-205e0552af0e.png)

I am able to run the Main.java file on my PC and it does import the Scanner correctly. I'm still confused as to why im getting this error.

**Comment by glennljs** [comment]
I believe that for the actual project you should be using the `String[] args` of your Main class to parse inputs and not Scanner.

For example, if the input is `java Main 1 2 3 4 5`, args[0] will refer to 1, args[1] will refer to 2 etc... 

Keep in mind that the type of these arguments are String so you would need to parse them accordingly.

**Comment by roopaniedu** [comment]
Thanks! Unfortunately I'm met with another error:

![image](https://user-images.githubusercontent.com/66832279/99236588-5d140100-2832-11eb-8976-a59f56ccffed.png)
Again this error does not make sense to me because it works perfectly fine on my PC.

**Comment by CWei88** [comment]
It seems like when you execute the Leave Event for customer 5, it returns a null in the queue. Maybe you can look at preventing the null from being added to the queue

**Comment by roopaniedu** [comment]
Thanks alot everyone! Issues have been resolved :)
