### ISSUE TITLE
Project 2 Level 6 

### ISSUE THREAD

**Issue by zimmmz** [nus-cs2030/2021-s1#395]
Hi, may I know why from customer 16 onwards all the customers will leave? 

As from what I see self-check 3 does not have any waiting customer at the moment so shouldn't customer 16 get assign to wait for self-check 3? Any help is appreciated, thanks in advance :) 

![image](https://user-images.githubusercontent.com/70898344/99294018-6e82fa80-287e-11eb-88eb-e2cca27ab293.png)

**Comment by jerimiglo** [comment]
this is because self-check 2 and self check 3 have the same queue despite having different numbers! this is because all self check counters only have **one shared queue**. Since 14 and 15 are waiting to be served by self-check 2, the qmax (2) is reached and no other customers can queue at the self-check counters. Since 10 and 11 are waiting to be served by server1, customers cant queue at server 1 too so they all leave !

**Comment by marcuspeh** [comment]
The self checkout have a common queue so the queue for each self checkout is the same. You could also think it this way, only the first self checkout has a queue, the others dont

**Comment by zimmmz** [comment]
ahh okay i think i got it. Thanks alot ! @jerimiglo @marcuspeh
