### ISSUE TITLE
Project 2 Level 4 

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#405]
I'm not too sure why my code does not output the testcase correctly ( testcase as shown in level 4 ). Both 9 and 10 are served at the same time even though its not supposed to be that way. Any ideas?

![image](https://user-images.githubusercontent.com/66832279/99395603-a2f8c400-291b-11eb-8c03-4de393d7e240.png)

**Comment by KaushikR1999** [comment]
Before your ServeEvent is printed/executed, check if the time of the event and nextAvailableTime of the server match

**Comment by tlylt** [comment]
Should be due to the waiting queue and the way timing for ServeEvent is determined (probably within your WaitEvent.java).

**Comment by roopaniedu** [comment]
I'm so sorry but i am still lost as to how to do this

**Comment by kennethkks** [comment]
When you encounter a serve event you should check if the time is accurately updated before printing. If the time is wrong, you can pass in the new serve event with the correct time into the pq

**Comment by kennethkks** [comment]
Btw i think ur comparator might have an issue 9 should be printed before 10 for the serve events

**Comment by roopaniedu** [comment]
> Btw i think ur comparator might have an issue 9 should be printed before 10 for the serve events

yep i managed to fix that part

**Comment by zimmmz** [comment]
@bitz-nobel  actl I think this happens because of both of customer is waiting to be served by Server 1 as seen over here. And after your cust 7 is done serving by server 1, your priority queue will have two serve event which is for your customer 9 and 10. So at your serve event u might want to check if the timing that the cust is supposed to be serve at is it lesser than the updated server nxt available timing if it is you might need to reschedule another serve event for your customer 10 in this case and the reschedule timing will be the time when customer 9 is done serving by server 1.

cus eg is that at 10.484 cust 9 will be served and the nxt available time will be 10.781 so when you reschedule your cust 10 to start at 10.781 instead of 10.484. And btw you can refer to #301 and #321 for more info on lvl4. hope it helps :)

**Comment by roopaniedu** [comment]
Thanks to all those who helped. I managed to finally finish Level 4 phew
