### ISSUE TITLE
Project Level 4 :(

### ISSUE THREAD

**Issue by hhhhanz** [nus-cs2030/2021-s1#413]
Hi guys I know there are a bunch of posts about this already but I still can't figure this out :( Would appreciate any help I can get.
![image](https://user-images.githubusercontent.com/70444061/99431491-d18b9480-2945-11eb-887f-80f83dcb2ccf.png)
![image](https://user-images.githubusercontent.com/70444061/99431519-dc462980-2945-11eb-97fb-75178b92f009.png)
![image](https://user-images.githubusercontent.com/70444061/99431550-eb2cdc00-2945-11eb-9dc7-b17f8c2aa1d1.png)

What I have now:
In WaitEvent: If queue is empty, return new ServeEvent with updated time. If not empty, return new ServeEvent with current time
ServeEvent: If current time == server's next available timing, return new DoneEvent with currenttime+svc time. If not, return new ServeEvent with currenttime+svc time.

**Comment by zimmmz** [comment]
@hhhhanz hii idk if this will be of any help. from the second ss i saw that your allocation of servers rn is wrong since cust 10 shld be waiting to be served by server 1 instead of server 2. Maybe you can try to check on your qmax implementation as one server shld be able to have max of 2 waiting customer for the testcase in ur second ss but frm wat i see now is that ur server maybe only can have one cust waiting in queue thats why cust 10 waits for server 2 instead of server 1. 

I think for ur first ss shld be the same issue regarding qmax too since cust 3 shld waits to be serve by server 1 but for ur codes it will generate a leave event instead.

**Comment by kah0210** [comment]
"If not empty, return new ServeEvent with current time" <- this should not happen as a customer should immediately go to serve event from arrive event, if the server is available. by returning a new serveevent with current time, it implies waiting time = 0 and there is no need for the wait event.
WaitEvent should only be returned from ArriveEvent if no servers are available AND if there is a server with no waiting customer yet (assuming ure at level 3, else: if there is a server with currentQ < qMax)

Perhaps you can change your server updating and event passing by doing the following in wait event:
Updated server: unavail, has waiting customer, +1 to qsize
return serve event with timing = server's next available time

In serve event, if server's NAT <= start time of serve event, update server accordingly and return a done event with current time + svc time

hope this helps!

**Comment by hhhhanz** [comment]
@zimmmz @kahehe hi guys, i managed to get it! tysm :)
