### ISSUE TITLE
Project 2 level 2 understanding

### ISSUE THREAD

**Issue by adelineT-jy** [nus-cs2030/2021-s1#418]
Hi, I am quite confused as what I am supposed to get our of level 2. It says that subclass of an Event can only have properties. What does it mean?
![image](https://user-images.githubusercontent.com/72067023/99477401-6665b080-298d-11eb-9b79-f337205d2853.png)

I am currently having this error so I believe it is related to the question I asked. Anyone can explain to me? Thank you!
![image](https://user-images.githubusercontent.com/72067023/99477480-8a28f680-298d-11eb-85aa-997c2cadd552.png)

**Comment by merylseow** [comment]
I believe `public Pair<Shop, Event> execute(Shop shop)` should be a method only in Event class and not all the subclasses of Event. For each subclass, you can think of how to fit your current execute() implementation as a function that will be passed into the subclass' constructor. Hope this helps!

**Comment by sharleneq** [comment]
As merylseow mentioned, `execute()` method is only in the Event class. So your subclasses of Event (eg. ArriveEvent, ServeEvent etc) should only contain properties (eg. `private final int serverIdentity` or whatever your design requires), a constructor and at most 1 `toString()` method. No other methods in the subclasses.

**Comment by hengyiqun** [comment]
I think it means that each subclass of events (e.g. ArriveEvent) can only constructors and also 1 toString() method.

**Comment by banchiang** [comment]
![image](https://user-images.githubusercontent.com/72375578/99478266-112a9e80-298f-11eb-9c8a-9f7782d17991.png)
Not sure about properties I think it means attribute in java. But basically in the subclass events (arriveEvent) there can only be **ONE** method which is the toString() method (for printing purposes). So in your arriveEvent there shouldn't be a execute method(error where arriveEvent contains other methods). How you can store the different execute method(function) in different event is to have a attribute Function<Shop, Pair<Shop, Event>> as stated in the **first** line of the screenshot. So basically storing your overriding execute method in your arriveEvent as an attribute in the Event class instead of writing a method in your arriveEvent class.
