### ISSUE TITLE
Project2 TestCase 4_4

### ISSUE THREAD

**Issue by banchiang** [nus-cs2030/2021-s1#420]
![image](https://user-images.githubusercontent.com/72375578/99478841-19cfa480-2990-11eb-832f-cd53251f2a57.png)

So for level4 where queue is introduced to the servers my code failed at test case 4 (a customer going to the wrong server, suggesting that smth is wrong with the queue implementation). The code is able to pass testcase4_1(maxQ = 1), 
testcase4_2 (maxQ = 2), testcase4_3 (maxQ = ?). 

How my arriveEvent transits to a waitEvent is when no servers are available, it will search for the first server with the queue that is not full (where a server queueSize < maxQueueSize). How I update my queue is when a customer waits at a server (waitEvent), queueSize of server increments by 1 and will be updated in the shop. When a customer is served (serveEvent), if my server that is serving has queueSize > 0, queueSize will decrement by 1 and the server is updated in the shop.

Yeah not sure where my code went off. Anyone can think of anything?

**Comment by LapisRaider** [comment]
Base on your test case, it seems that its saying server 1 queue list is not full, thus it goes to server 1 instead of server 2? You might want to check your conditional checks when picking which server to go to or do some prints.

The input for testcase4_4 if you want for easier debugging is: 2 5 10 1000 7 1 (You can reduce the 1000 to a smaller number of customers, first few lines will be the same )
I managed to get the input for it after doing a little trick that forces codecrunch to print out the input when I was having trouble at test case 4_4.

Hope this helps!

**Comment by kah0210** [comment]
Your code logic works but perhaps there are problems with the queue updating process.

You can print out the queuesize for each server everytime Main.java polls out a Wait/Serve event to check. This may help u identify the source of error better. Check that your Wait and Serve event updates the correct server as well. This can be done my obtaining the most updated server (obtain this from shop via serverid) and updating that instance of server instead. Hope this helps!

**Comment by banchiang** [comment]
Alright thanks guys! solved!
