### ISSUE TITLE
Project 2 – Level 4

### ISSUE THREAD

**Issue by yusufaine** [nus-cs2030/2021-s1#432]
# Description 
I'm now encountering an issue with my waiting customers where once the server is available, (in this case) both customers 9 and 10 are being served. I thought it was a problem with how I stored and called the waiting customers but even after checking that, the problem still persisted. Any help would be appreciated 😞 

## Output: 
![image](https://user-images.githubusercontent.com/29030941/99561824-5936d900-2a02-11eb-961b-0aa259edd92e.png)

The output properly shows 9 being served and was taken out of the queue but 10 remains (and is apparently being served alongside Customer 9)

My intended event-flow in this instance was: 
```
arrive > wait > serve(7) > done (7) > 
(queue check) (get 9) serve 9 > done (9) > 
(queue check) (get 10) serve 10 > done (10)
```

**Comment by zimmmz** [comment]
@yusufaine hii did you tried to reschedule your cust 10? Due to qmax both the customer is waiting for the same server at the same time now. So based on your event comparator cust 9 will be get served first hence server1 next available time will change to 10.781 when cust9 is served. But cust10 does not know it since when it came in to wait, the server's next available time was 10.484 thats why both cust got served at the same time. 

You might want to consider to check if the time of the event and next available time of the server match if it is doesn't you can reschedule a new serve event for cust 10 with the server's updated next available time. hope it helps. :)

**Comment by dljw98** [comment]
You need to implement a way to delay your ServeEvent to take into consideration that the Server is serving someone else

**Comment by jiayi-lim** [comment]
You can check if the server is currently serving another customer by extracting the server with the same ID as the assigned server  for the customer from the shop and check if this extracted server next available time is <= the start time of serve event (aka server is free to serve your customer) before you serve.

**Comment by kheekheekhee** [comment]
I believe the problem is that you didn't account for the multiple people in queue. You have to add on to the Server's next available time for every person in queue so that the Server is only available once it has finished serving everyone in front
