### ISSUE TITLE
Proj2 level 4 

### ISSUE THREAD

**Issue by Mavvvvv** [nus-cs2030/2021-s1#452]
Hi can I ask how did you modify your server class to do level 4. 
Previously my server was Server(int identifier, boolean isAvailable, boolean hasWaitingCustomer, double nextAvailableTime)
I changed it to public Server(int id, boolean isAvailable, int maxCust, Queue<Customer> custQueue, double nextAvailableTime)  to do level 4. 
When I tried submitting to code crunch I couldn't pass the previous levels. Was I not suppose to change my server class for level 4.

**Comment by merylseow** [comment]
I think you can't remove your previous constructor since the past level's test cases in Codecrunch will use this constructor `Server(int identifier, boolean isAvailable, boolean hasWaitingCustomer, double nextAvailableTime)`. 
Eg. `jshell> Shop shops = new Shop(List.of(new Server(1, true, false, 0), new Server(2, false, false, 1.0)))`
Maybe try overloading?

**Comment by limyapkai** [comment]
Yup agree, need to Overload the Constructor!

**Comment by sharleneq** [comment]
Yep, you should overload your constructors. In the constructor with less attributes, do remember to initialise the others found in the constructor with more attributes. For eg, the constructor with less attributes`Server(int identifier, boolean isAvailable, boolean hasWaitingCustomer, double nextAvailableTime)` still need to initialise the other attributes: ` this.maxCust = maxCust;` and `this.custQueue = custQueue;`.

**Comment by patriciafzy** [comment]
Apart from overloading your constructor, you need to make sure your main method is still able to pass level 3 as well (aka overloading the main also)!

**Comment by Mavvvvv** [comment]
okay thank you!! I overloaded the method and it worked!
