### ISSUE TITLE
Project 2 Test 6_8

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#453]
Hi, I've got the following error:
![image](https://user-images.githubusercontent.com/66832279/99780178-120b2e00-2b51-11eb-8f73-236fa1561e0e.png
![image](https://user-images.githubusercontent.com/66832279/99780204-1df6f000-2b51-11eb-99e8-ceec2bd559a1.png)

Also does anyone happen to have the test case for this? My error is so long!

**Comment by ClementNgZiQian** [comment]
If you look at lines 233 and 234, both self-check 4 and 5 have done serving their prev customer, so the deal breaker for the next customer in line for the self checks will be the one with the smaller identity number, which is 4, and it appears the timing for serving 78 is self-check 5's next available time instead of his arrival time.

**Comment by jiayi-lim** [comment]
You might want to check how you choose your server and remember to take the first one if you check the availability according to their IDs. The choosing of the right server should be in your arrive event. 
As for the wrong timing for serving 78, you can do Double.max(customer's arrival time, chosen server's next available time) to output the right timing. 

Hope this helps!

**Comment by roopaniedu** [comment]
Thanks so much! You both are right, turns out that my ServeEvent.java replaced my sc 4 with sc5 because sc5 nextAvailTime was smaller than sc4. Once I fixed that, it worked!. 

For anyone who needs it :
![image](https://user-images.githubusercontent.com/66832279/99791627-d5dfc980-2b60-11eb-93a7-1ab4e9d3e548.png)
