### ISSUE TITLE
Project2 Level6

### ISSUE THREAD

**Issue by banchiang** [nus-cs2030/2021-s1#456]
Hi I'm attempting level6 and im encountering the error for the third test case given at level6.
![image](https://user-images.githubusercontent.com/72375578/99784020-26055e80-2b56-11eb-8807-39293428e52b.png)

So basically, the sequence of event is jumbled up thats why theres an error and I'm not sure why.

My eventComparator first compares the timing (earlier time), then type of event, then the customerID (smaller ID goes first).

How I update the serveEvent (to allow the Servers to be update to date) is to check the followings, 
1. if eventServer is not up to date to shopServer, update it (pack into new serveEvent)
2. if eventServer is an instanceof SelfCheckOut, check if its the best selfCheckOut (earliest timing), if not update it.
3. if 1 and 2 are okay, the serverEvent is ready to be executed and it will generate the customer service time.

So yeah, not sure where went wrong :X

**Comment by jiayi-lim** [comment]
The timing that 10 was done serving is also wrong though!! This explains why your 11 done serving is also wrong. Both 10 and 11 are using human server (server 1). I am suspecting that in your serve and done event, you have accidentally updated human servers when you not supposed to!

**Comment by guccilerino** [comment]
I had the same issue before even when my comparator had no issues. My issue was due to my chaining of events not having referenced the correct timings. The chosen server of the event should always be drawn from the shop to ensure that it is the most updated one. Do check your subclasses of events to see if all the events are chained properly with the correct timing.
