### ISSUE TITLE
CompletableFuture vs Thread

### ISSUE THREAD

**Issue by LapisRaider** [nus-cs2030/2021-s1#460]
So I've been looking through using Thread and CompletableFuture, and from what I understood, completableFuture runs in a thread that is pre-allocated thus making it more memory efficient compared to Thread where we have to manually manage the thread. 

However, my main question would be why if I call thread.run() without doing thread.join(), my program would still execute and complete the thread. Whereas for completableFuture, if I do not do .join(), my program just finishes and do not execute and complete the thread at all? 

I've attached a screenshot to better explain what I'm asking. I tried searching online but so far can't find anything. If you guys know any more differences between using thread and completableFuture please let me know too.

![completableFuture](https://user-images.githubusercontent.com/36361212/99839815-5248cb80-2ba6-11eb-992b-d3d1a50d3cf3.jpg)

**Comment by waynetee** [comment]
Probably because completablefuture uses daemon threads which are terminated when your main exits.

**Comment by charoi** [comment]
Hi @LapisRaider ,

I think the join method may be doing different things.
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html
Returns the result value when complete, or throws an (unchecked) exception if completed exceptionally. (returns T value)

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html
Waits for this thread to die. (returns void)

Not fully sure but I think for CompletableFuture it is a promise that the action will be done... so the JVM will continue executing the next lines of code expecting the completableFuture to be done in the future... whereas for Thread its not a promise but its more parallel computation?
Ofc if i am wrong pls do clarify with me, this chapter confuses me too :,)

**Comment by TypeDefinition** [comment]
There are 2 types of threads in Java. User threads, and Daemon threads.

Daemon Threads:
Daemon threads are low priority threads that are mainly used to run background tasks. They do NOT prevent JVM from shutting down. When JVM wants to shutdown, it terminates any daemon threads even if they are still running.

User Threads:
A user thread is a high priority thread. When JVM wants to shutdown, it will wait for all user threads to finish executing before shutting down.

Conclusion:
Since CompletableFuture runs on a daemon thread, its process is terminated when the main function ends.
On the other hand, the thread you created is a user thread. And thus JVM will wait for it to finish.
You can toggle your user thread into a daemon by calling setDaemon(true). You will then see the same result as using CompletableFuture.

Stack Overflow:
https://stackoverflow.com/questions/22146899/how-can-thread-run-after-main-method-closes

Daemon Threads vs User Threads.
https://beginnersbook.com/2015/01/daemon-thread-in-java-with-example/

**Comment by LapisRaider** [comment]
Thanks, @TypeDefinition and @waynetee ! Looks like it really is due to the daemon thread, I tried doing setDeamon(true) for the normal thread and the behaviour became similar to that of the completableFuture. Thanks!
