### ISSUE TITLE
Project 2 Level 5 2nd Test Case

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#469]
Hi, i've been trying to figure why 17 doesn't queue for 2. Based on what i've output at the start of each ArriveEvent from the latest shop's servers, in this format:
```java
[serverID, isAvailable, nextAvailableTime, queueSize]
```
17 should rightfully queue for 1 as 1's queue is not filled, but i'm definitely wrong as my output doesn't match the one in level 5

The one in Red is my output, the one in Teal is from Level 5 2nd test case.

![image](https://user-images.githubusercontent.com/46486515/99886052-7f63af80-2c74-11eb-9919-d68322c2c1bd.png)

Appreciate any help, thank you!

**Comment by CWei88** [comment]
Looking at the test case, both 13 and 16 are queueing at Server 1, while Server 1 is taking a break. Hence, the queue for Server 1 should be full and when 17 arrives, it should see that Server 1 queue is at maximum capacity (2 people, 13 and 16). That's why it queues at 2. 

You might want to look at your queue when the Server is taking a break.

**Comment by domlimm** [comment]
Hi @CWei88 thank you for your input! Definitely gave me a clearer picture of what's happening. I just started taking a look at it again and it kinda fixed itself, not knowing how, must have changed something before i stopped earlier in the morning haha
Thank you so much though!
