### ISSUE TITLE
Project 2 Level 6 Test Case 2

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#476]
Hi, I'm not sure why **@15.940 18 waits to be served by 1**? (CC's output shows that but mine outputs as **@15.940 18 served by 2**)

The one in **Red** is **my output**, **teal** is **CC's level 6 test case 2**.

Print out of all servers in the Shop are as follow:
```java
Arrive Event: [serverID, isAvailable, nextAvailableTime, queueSize, isSelfCheckout ...]
```

![image](https://user-images.githubusercontent.com/46486515/99900912-c3df6180-2ced-11eb-826d-ae100190fa07.png)

Additionally, I submitted my codes and it's odd that i'm on test6_5 when I have yet to pass the ones in CC...

![image](https://user-images.githubusercontent.com/46486515/99900926-db1e4f00-2ced-11eb-951f-ec39099ca0fd.png)

Any input is appreciated, thank you

**Comment by benluiwj** [comment]
looks like the server is supposed to go rest. It could be possible that your server rest period is one ahead than it should be.
for the cc case, I don't think it goes in order tbh. the platform test cases may not be that they show to you

**Comment by patriciafzy** [comment]
Hi, I am not too sure about your very first testcase but I agree with benluiwj that it seems that the server was supposed to rest but didnt. Can I have the input and I can check for you? 

As for testcase 6_5, I had that error previously and the problem was because the queue for self-checks are not updated. What I did to fix it was I created a variable int `queueLength` storing the number of customers. When the customer is supposed to be served by selfcheck, I +1 to this int and -1 when this customer is served. When every event is polled, I update the first selfcheck server (just changing one will do because it's a shared queue)'s number of customers according to this `queueLength`. We might have different approaches so I am not too sure if this works for you but perhaps you could try printing out the number of customers in the self-check to check if it is indeed updated. 

In addition to what you replied on my thread, 
_" i suppose your Event class has a Server variable and a getter for it?"_ >> yes, all my events (except arrive and leave) have a server so that it's easier for me to "get" the server from them and check if its self-check.

**Comment by domlimm** [comment]
Hi @patriciafzy here it is,

```java
java Main 1 2 1 2 20 1.0 1.0 0.1 0.5 // CodeCrunch Level 6 2nd Test Case
```

that's very kind of you! Thank you :')

I've read and thank you so much for your reply!

**Comment by patriciafzy** [comment]
Hi, I've tried running it and indeed benluiwj is correct and the Server 2 is supposed to rest and hence, 18 should wait to be served by 1 instead. You might want to check your code about the Server Rest! 

<img width="300" alt="Screenshot 2020-11-22 at 7 29 07 PM" src="https://user-images.githubusercontent.com/65544605/99902488-25f19400-2cf9-11eb-94dd-56f5d47c9acd.png">

**Comment by benluiwj** [comment]
@patriciafzy nice printf statement HAHAH can see the rage

**Comment by domlimm** [comment]
HAHA thank you @patriciafzy !!! weird it doesn't print on my end. i guess something to check on... 👍🏻
