### ISSUE TITLE
Project 2 Level 3

### ISSUE THREAD

**Issue by kohkenneth** [nus-cs2030/2021-s1#482]
Hi there anybody has any suggestions on how one can go about attempting project 2 level 3? I dont really understand how I can make use of the Lazy concepts to attempt this level. Right now i'm thinking if i should code everything in the Main.java file or creating another class (e.g. simulator class or something) to be in charge of running the simulator. Or any other suggestions would be great thank you!

**Comment by chuashiqi** [comment]
i created another class within the package to do my implementation since RandomGenerator cannot be accessed in Main.java. 
as for Lazy, i passed Lazy.of(() -> rg.genServiceTime()) through my ArriveEvent all the way until ServeEvent. You have to do this so that the service time will only be generated when the customer is served. another option would be to directly pass RandomGenerator and call genServiceTime() when serving. Make sure to put your Lazy.java in the package as well if you choose to do the Lazy method.

**Comment by jedlwk** [comment]
I did similar to @shhiiiqqqqiiiii where my Main.java class is used to define the parameters of all the various int and double. I then created another class within my simulator such that my Main.java will initialize the class to run the whole simulation. This is so as to adhere to the Single Responsibility Principle (SRP) where each class is responsible for one purpose. 

Similarly, my activation of genServiceTime() is at my ServeEvent class where I initialize an Event that takes in a serviceTime that I derived from genServiceTime().

**Comment by kohkenneth** [comment]
@shhiiiqqqqiiiii @jedlwk Thanks for the replies! Do you guys have any suggestions other than using Lazy in terms on implementation? I'm not very confident in the Lazy implementation and I'm afraid I might face more issues in the further levels. Thanks anyways!

**Comment by chongweil907** [comment]
You can encapsulate the RandomGenerator inside Shop so you wont need to create a class specifically for RG. Hope this helps

**Comment by jedlwk** [comment]
Personally, I didn't use the Lazy method to solve this level. My core implementation in my ServeEvent class is that I will return a Pair<Shop, Event> which in this case will update the shop and return a Done Event after serving. 
This is my return for your reference!

```
return new Pair<>(
           shop.replace( shop.getServer( server.getID() - 1).serve( startTime, serviceTime ) ), 
           new DoneEvent( customer, server, startTime + serviceTime)
                 );

```
Take note that you would have to update the shop before returning a new pair in each execute! Hope this clarifies!``

**Comment by hengyiqun** [comment]
Like @shhiiiqqqqiiiii, I created another class within the package to use RandomGenerator. I encapsulated it into customer, so that I am able to obtain the arrival interval for each customer. During each event, I get the random generator again to generate the required values such as the service time interval and rest time interval etc.

I think there's quite a few possible implementations. Not really sure which one is the best, so you should choose one that you think that fits you or that you understand best.

**Comment by TarciusW** [comment]
you can just reuse the code you did in project 1. just be sure to take note of the following constraints.
1. event class can only have a constructor and tostring method
2. the randomgenerator class can only be accessed within the package. so you can consider wrapping it in a public class and accessing it though there. 
3. the 'lazy' method just needs to ensure that service time only gets called when a customer is being served. so you can think of including it with your serveevent

all this should cut your main code as compared to project 1 by a lot but it takes awhile to change verything

**Comment by oolongmilkteax** [comment]
Like a few others, I also created another class which is essentially the RandomGenerator class with exactly the same methods to allow access of the methods in the Main class. 
Instead of using Lazy, my Event constructor takes in the random generator so that it's methods can be called upon when needed.

**Comment by byronyip1998** [comment]
hi kenneth you can refer to 
https://github.com/nus-cs2030/2021-s1/issues/377
and
https://github.com/nus-cs2030/2021-s1/issues/459

to help you too!

**Comment by byronyip1998** [comment]
hope it helped ! all the best for finals kenneth 

> hi kenneth you can refer to
> #377
> and
> #459
> 
> to help you too!

**Comment by kohkenneth** [comment]
@byronyip1998 @oolongmilkteax @TarciusW @hengyiqun @chongweil907 @jedlwk thanks for your input guys ill try the methods out hopefully it works!
