### ISSUE TITLE
Typecasting when checking for equality

### ISSUE THREAD

**Issue by kohkenneth** [nus-cs2030/2021-s1#484]
Hi guys can anyone explain to me the purpose of typecasting when checking for equality? 

For e.g. after checking (obj instanceof Point), won't obj be able to use Point methods already? Since obj is a Point. Why do we still have to typecast using 'Point p = (Point) obj'. Apologies for the trivial question but I am quite confused. Thanks in advance!

**Comment by marcuspeh** [comment]
The equal function takes in an Object so when a Point is passed in, it is actually type converted to an Object and it wont be able to use Point methods. As such, it needs to be type casted back to a Point to use it

**Comment by jedlwk** [comment]
The point of you overriding an equal method is because you cannot simply `if(Point1 == Point2)`. 

Since you are overriding a method, once you check that the Object is an instance, you need to further make sure that your method signature is the same. In other words, when you want to verify if Point p = obj or vice versa, you need to cast it with a (Point) so that your compiler knows that it is a (Point) and not anything else (which is mentioned by @marcuspeh )

Only when you cast it, then you can use whatever method you're using to compare those values.

**Comment by kohkenneth** [comment]
@marcuspeh @jedlwk Thanks a lot for the explanation I think i understand it better now!
