### ISSUE TITLE
Project 2 Level 6_5

### ISSUE THREAD

**Issue by limyapkai** [nus-cs2030/2021-s1#495]
Does anyone happen to know the inputs for test case 6_5? Been stuck at debugging this problem. 

![image](https://user-images.githubusercontent.com/27536739/100301570-5a07d600-2fd3-11eb-91c4-b9c00dad4965.png)

**Comment by gabrielloye** [comment]
Not sure of the exact inputs but looks like there's 0 human servers and only self-checkout servers. From your output, you may have to modify the way you handle the wait event since 'we always say that the customer is waiting for the self-checkout counter k + 1', i.e. the '4 waits to be served by self-check 2' statement should not appear since the waiting should be done with self-checkout 1.

**Comment by sharleneq** [comment]
I do not know the exact inputs, but perhaps you can check if your self-checkout counters' shared queue is implemented correctly? Because it seems that the maximum number of customers allowed to queue for self-checkout counter is 1 (customer 3 is already waiting as customer 1 and customer 2 are being served), which meant that customer 4 should leave and not wait. Also, as mentioned above by gabrielloye, do remember to change your printed output for WaitEvent as it should always be waiting for the first self-checkout counter.

**Comment by limyapkai** [comment]
@gabrielloye @sharleneq  Thank you for the enlightenment! I overlooked the k+1 and now got it "waits to be served by self-check 1"

Can I clarify so the MaxQueue applies to the Self-Checkout Counter (regardless the number of sub-counters that are available in the Self-Checkout ) correct? 

I thought  my codes already did that though Hmmmm

**Comment by gabrielloye** [comment]
> Can I clarify so the MaxQueue applies to the Self-Checkout Counter (regardless the number of sub-counters that are available in the Self-Checkout ) correct?

Yep, all Self-Checkout counters share the same queue so there can only be `MaxQueue` number of customers waiting across all of them.

> I thought my codes already did that though Hmmmm

Perhaps can try printing the queue lengths/contents of the server at each event/iteration to check whether the queue is being checked properly? You can create temporary getters to debug it this way.

**Comment by sharleneq** [comment]
Yeap! So in this case, the maximum number of customers is 1 therefore your 2 self-checkout counters can only have 1 waiting customer in total. Perhaps you can also print Shop to see the relevant status of the self-checkout counters, to see if they're correct as you designed.

**Comment by limyapkai** [comment]
Thank you! So apparently, the bugg was caused by the Self-checkout counter. When it was maxQueue is reached, only the particular self-checkout counter was changed to hasWaiting = True while the rest of the self-checkout counters are indicated as = False. That's why, the Queue continues and did not perform as expected.. zzzzz . Managed to resolve it by doing a Queue size check at the Arrive Event in order to direct the arriving customer to leave. @gabrielloye  @sharleneq  Thank you for the inputs !

**Comment by sharleneq** [comment]
Yay glad you solved it :-) Atb w the rest of the project!

**Comment by limyapkai** [comment]
@sharleneq Sighhh... java's complexities... but still, Thank you for the encouragement!
