### ISSUE TITLE
Recitation 10 Q1

### ISSUE THREAD

**Issue by varshanaa** [nus-cs2030/2021-s1#497]
Hi, does anyone have a simpler way of explaining how to do this qn? I don't really understand the solution in the guide
<img width="549" alt="Screenshot 2020-11-26 at 2 39 02 PM" src="https://user-images.githubusercontent.com/65850075/100316575-c3004580-2ff5-11eb-8fb2-d33add911817.png">

**Comment by hongpeigoh** [comment]
**Methodology**
Essentially, this question will require you to create several methods:
1. Create a stream of numbers
2. Find the factors of each of this number
3. Check if the factors are prime

If we think of this in simple terms we can interpret each of these as individual problems to solve. Let's look at the version of these solutions without using streams.

**1. Create a stream of numbers from 1 to n**
```
List<Integer> list = new ArrayList<Integer>();
for (int i = 1; i < n + 1; i++) {
    list.add(i);
}
```

If we now think of passing this into a stream, we can use IntStream, which provides a simple way to do this, we simply give it a range from 1 to n+1, and it will create a stream of integers from 1 to n (excludes n+1).
```
IntStream.range(1, n+1)
```

**2. Find the factors of each of this number**
To find the factors of a number, we run a for loop through every number smaller than said number and check if the remainder (%) is 0. One would be familiar with the simple programming solution using a for loop.
```
List<Integer> factors = new ArrayList<Integer>();
for (int d = 1; d <= n; d++) {
    if (n % d == 0) { factors.add(d); }
}
```

It will be easy to notice that essentially we can convert a for loop into a stream as we did in 1. Moreover, the if statement within the for loop is essentially a test (or a Predicate) to see if it satisfies the given condition (n % i == 0). So summarily, that is how they arrive at
```
IntStream
    .rangeClosed(2, x) // Closed to include x
    .filter(d -> x % d == 0) // if x % d == 0, include d in the stream
```

**3a. Check if a number is prime**
Before we check if the factors are prime, we see how we check for primes again.
```
List<Integer> primes = new ArrayList<Integer>();
for (int i = 2; i < n; i++) {
    boolean isPrime = true;
    for (Integer p: primes) {
        if (i % p == 0) {
            isPrime = false;
        }
    }
    if (isPrime) { primes.add(i); }
}
```
This may feel a bit cumbersome because we have to check back to the list of primes to see if you should add this to the list of primes. However, IntStream implements a method known as noneMatch which essentially checks back against all the terms that have been evaluated in the stream. This is what is meant in the `isPrime` method:
```
IntStream
    .range(2, n) // We only start from 2 because 1 is not prime
    .noneMatch(n -> n % x == 0) // if no x from the current stream of primes matches n % x == 0 (x not a divisor of n), include n
```

**3b. Filter for prime factors**
Essentially if you compose the functions of finding factors along with checking whether they are prime, you will be able to return the prime factors. Here, they use the syntactic sugar of a lambda expression to return a predicate (test if divisor d is prime)
```
factors(x) // stream of factors
    .filter(d -> isPrime(d)) // filters all the factors to only return those that are primes
```

**Conclusion**
If we combine all these abstracted functionalities, it would be easier to interpret the final method. The final lambda counts the number of prime factors as calculated in 3b. As such, these low level functionalities are combined to create a general solution. Ultimately, this abstraction and packaging should make it simpler for you to understand each part and how they work together. Another useful tip is that streams work like for/while loops* (with a big asterisk). If you can create something within a for/while loop, it would usually be possible to generate a stream!

Hope this helps!

**Comment by varshanaa** [comment]
thank you so much! :)
