### ISSUE TITLE
Lab 3 Codecrunch output error

### ISSUE THREAD

**Issue by kaiyang96** [nus-cs2030/2021-s1#51]
![WhatsApp Image 2020-09-11 at 11 14 12 PM](https://user-images.githubusercontent.com/71059104/92943203-15b17300-f485-11ea-95f4-aedf8e621bf9.jpeg)

Seeing as my error is missing the ".. ==> $" from my System.out.println, I made the addition and it passed the codecrunch test.

However, to my understanding, isn't the "$.. ==>" part of the jshell output, which is more of an indentation to show us the result of what we keyed in. Pretty sure it isn't intended to be part of the System.out.println(...), so I'm pretty confused.

**Comment by lkldev** [comment]
Hi, I believe we are not supposed to use `System.out.println` based on the output in level 5, since the output shows `$.. ==>` which indicates that an object is displayed into the console instead of using `System.out.println` to print the output. An example would be as shown below:
![image](https://user-images.githubusercontent.com/49238386/92949469-b60b9580-f48d-11ea-95c8-7fd90abc306a.png)

If I use `System.out.println` to print the String object, it will be printed without the `$.. ==>` indicator. However, if I attempt to print the object via the console without `System.out.println`, it will be printed with the `$.. ==>` indicator. Hope this helps. :)

**Comment by rickyaandrew** [comment]
i got another issue here, i tried returning a String, and return Booking.toString() instead, but the result gave me this
![image](https://user-images.githubusercontent.com/67989509/92985798-9fdef300-f4e8-11ea-8731-13adac46dc94.png)

**Comment by rohit0718** [comment]
@darkinguy check the return type that the question asks for! is it supposed to be a String?

**Comment by rickyaandrew** [comment]
@rohit0718 ohh my HAHAH sorry i got it now thanks a lot!

**Comment by kaiyang96** [comment]
> Hi, I believe we are not supposed to use `System.out.println` based on the output in level 5, since the output shows `$.. ==>` which indicates that an object is displayed into the console instead of using `System.out.println` to print the output. An example would be as shown below:
> ![image](https://user-images.githubusercontent.com/49238386/92949469-b60b9580-f48d-11ea-95c8-7fd90abc306a.png)
> 
> If I use `System.out.println` to print the String object, it will be printed without the `$.. ==>` indicator. However, if I attempt to print the object via the console without `System.out.println`, it will be printed with the `$.. ==>` indicator. Hope this helps. 

I see now, thanks alot for the clarification!!
