### ISSUE TITLE
Completable Future 

### ISSUE THREAD

**Issue by FergusMok** [nus-cs2030/2021-s1#517]
When converting normal code to asynchronous code, what is stopping me from simply wrapping my entire code in a CompletableFuture? Will I be violating any principle, or cause any problem? 

An example will be with this question : 
![image](https://user-images.githubusercontent.com/10182564/100466817-7f4c2f80-310c-11eb-9260-706ee0b3f65c.png)

And the answer 
`public CompletableFuture<LoginStatus> userLogin(String username, String password) {
    return CompletableFuture.supplyAsync( () - > /*the rest of the original function */ );
}`

**Comment by tlylt** [comment]
I wonder if that is actually an acceptable solution since you are indeed returning a CompletableFuture 😂 .
If you simply create a method that returns a CompletableFuture, when you do 
```java
CompletableFuture<LoginStatus> futureLoginStatus = userLogin(abc, zyx);
System.out.println("Some other code");
```
the program will not wait for `userLogin` to complete and hence the main program is non-blocking 
=> those codes below can be executed => "Some other code" is printed immediately.
However, if there is a need to use the result of `userLogin` somewhere below, you may still need to wait for a considerable time before it is completed. This is because within the new separate thread that the `userLogin` logic is run, it is running synchronously. 

So instead of clearing the roadblock from the Main driveway, can we really just move the roadblock to a separate driveway and call it a day? (let say we have 10 cars going down the Main driveway, now even though we bring the roadblock to a separate driveway, 8 of the cars are also now directed to the separate driveway with the roadblock, hence still problematic)

I think within the `userLogin`, there are methods that can be done asynchronously, such as `usernameExists()` and `isValidPassword()`, if you also make them run in a CompletableFuture, the code will probably run faster.

This is probably analogous to clearing the roadblock from both the Main driveway and the separate driveway.

**Comment by SkyBlaise99** [comment]
@tlylt i think you mean
`CompletableFuture<LoginStatus> futureLoginStatus = CompletableFuture.supplyAsync(() -> userLogin(abc, zyx));`

**Comment by tlylt** [comment]
> @tlylt i think you mean
> `CompletableFuture<LoginStatus> futureLoginStatus = CompletableFuture.supplyAsync(() -> userLogin(abc, zyx));`

I am referring to the `userLogin` method defined by OP
![image](https://user-images.githubusercontent.com/41845017/100493863-8576f600-3176-11eb-8fee-f94002b69dc1.png)

**Comment by FergusMok** [comment]
@tlylt Ah yes, making the usernameExists and isValidPassword into completableFutures, and then joining them at the if-statement will increase the speed, only in the case that those 2 methods take alot of time, which was specified in the question. And do the same for doLogin. 

I understand now, thanks alot.
