### ISSUE TITLE
Lab 8 Level 3

### ISSUE THREAD

**Issue by ghost** [nus-cs2030/2021-s1#524]
# Description 
Does Lab 8 Level 3 have nested CompletableFutures?

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/61898858/100495433-cb3bba80-3186-11eb-869c-3773d8a0c0cc.png)

**Comment by simxl** [comment]
Map<BusService, CompletableFuture< Set< BusStop > >> should suffice

**Comment by elizabethh07** [comment]
I only added CompletableFuture for the BusStop.
final Map<BusService, CompletableFuture<Set< BusStop >>> services;

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/61898858/100495712-2cfd2400-3189-11eb-9be4-67c944f60450.png)

Since the first part returns a CompletableFuture< Set< BusStop > >, how did you guys manage to make a Map < BusService,CompletableFuture < Set< BusStop > > > without using get() or join()?

**Comment by zechajw** [comment]
You won't need to get() or join() to make a map of busservice, completablefuture<Set<BusStop>> precisely because the value is stored in a completablefuture, which means u dont have to join() to get the value but rather can just modify it based on the completablefuture methods (thenapply, thencompose).

**Comment by ghost** [comment]
Sweet got it, thanks fam! :D
