### ISSUE TITLE
AY19/20 Sem 2 Question 2 - Stack and Heap

### ISSUE THREAD

**Issue by wongzw** [nus-cs2030/2021-s1#527]
# Description 
Hi! I'm attempting Question 2 from last semester's final assessment paper and I am not sure how to begin approaching this question/whether my answer is correct. Hope to get some inputs on this to ensure I'm approaching this correctly :)

## Topic: 
Java Memory Model

## Screenshot of Question: 

![image](https://user-images.githubusercontent.com/53685088/100496839-68e8b700-3192-11eb-9975-5083d70b2baa.png)

**Comment by lkldev** [comment]
Hi, how I approach this problem would be first to look at the various classes and their constructors. This would give me an idea as to which instances can be created. Then I look at the diagram to see what the variables are referencing to and assign those that are straightforward, in this case, `bk` and `br`. Since the `Library` class does not have a constructor that initializes the loan instance and `lib` is the first variable called (question state stack frame declared accordingly from top to bottom, i.e. newer variables are at the bottom), one can assume that `Library` class is created with the `Loan` instance in `Library` pointing to a `null` before being instantiated later. Thus, my answer would probably be:
```
Library lib = new Library();
Book bk = new Book("Book Title", "Sam");
Borrower br = new Borrower("John", 1234);
lib.loanBook(bk, br);
```
This is a way I can think of that would suit the stack and heap diagram.  Hope this helps :)

**Comment by dandaandaaaaaan** [comment]
hi, the way i did this is as follows

everything in the stack has to be pointers to local variables, and since it is LIFO, the br object has to be created first, and thus the constructor for Borrower can be called
`Borrower br = new Borrower("John", 1234);`

next thing in the stack is bk, so likewise can create the next line
`Book bk = new Book("Book Title", "Sam");

and finally the last pointer on the top points to Library. Since library doesn't have an explicit constructor and only a loanBook method, then I would do it like this
`Library lib = new Library();
lib.loanBook(bk, br);`

thus my final answer is
`Borrower br = new Borrower("John", 1234);`
`Book bk = new Book("Book Title", "Sam");`
`Library lib = new Library();`
`lib.loanBook(bk, br);`

**Comment by e0420658** [comment]
hello so for this stack and heap which way should we be looking at it, from top to bottom as first declared to last declared? or are both solutions correct? 
because they said the variables are declared accordingly from top to bottom so it should be @lkldev solution?

**Comment by Henry-Yuan-He** [comment]
The stack is LIFO. If the order of the variables in the stack matters (not very sure), shall we create variables from bottom to up?

**Comment by dandaandaaaaaan** [comment]
> hello so for this stack and heap which way should we be looking at it, from top to bottom as first declared to last declared? or are both solutions correct?
> because they said the variables are declared accordingly from top to bottom so it should be @lkldev solution?

actually i missed that line lol yeah then i think his solution is correct, with the lib object created first, followed by bk, br, and then the loanbook
