### ISSUE TITLE
Lab 3 Level 4

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#53]
# Description 
Hi, may I ask if we've to use the things taught in lecture 4 for this level? I'm not too sure how to integrate **PrivateCar** into Booking.
I.e On paper **Booking** should've 2 constructors - `Booking(NormalCar, Request)` & `Booking(PrivateCar, Request)` but overloaded constructors don't work like that.

I'm guessing i should extend **NormalCar** and **PrivateCar** in my Booking class?

Appreciate if anyone could point me in the right direction, thanks!

This is how my Booking class looks like now.

```
public class Booking implements Comparable<Booking> {
    private final NormalCab normalCab;
    private final PrivateCar privateCar;
    private final Request request;

    public Booking(NormalCab nc, Request r) {
        this.normalCab = nc;
        this.request = r;
    }

    public Booking(PrivateCar pc, Request r) {
        this.privateCar = pc;
        this.request = r;
    }
}
```
EDIT:
And there's some kind of weird output after testing test3.jsh and everything output as per what's in level 3.
![image](https://user-images.githubusercontent.com/46486515/92997303-df3b2d00-f544-11ea-8d34-41dbf1f329d6.png)

**Comment by rickyaandrew** [comment]
since this lab focus on Inheritance and Composition, instead of having 2 constructors in your Booking Class, maybe you can try having a Driver Class, and both NormalCar Class and PrivateCar Class extends to Driver Class. In that case, your Booking Class will only need 1 constructor, Booking (Driver driver, Request req). Since Driver Class is the parent class for both NormalCar and PrivateCar, calling new NormalCar or new PrivateCar via Booking (Driver driver, Request req) will be valid. to add on, it is not necessary for Booking Class to implement Comparable, you can just implement a compareTo function in Booking Class which returns int

**Comment by domlimm** [comment]
Ahhhh right.. I get what you mean. How did i miss that out.. Thank you!!!
