### ISSUE TITLE
Lab 3 testcase 3 Output on CC

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#54]
Hi, I'm getting this output saying that there's no class `BookingStub`.

Has anyone encountered this?

![image](https://user-images.githubusercontent.com/46486515/93000605-0ea96400-f55c-11ea-9430-6aa284a7a35d.png)

I have also gotten the desired output from `test3.jsh`.
![image](https://user-images.githubusercontent.com/46486515/93001377-30f1b080-f561-11ea-9635-aac170ec7dde.png)

`test.4jsh` too!
![image](https://user-images.githubusercontent.com/46486515/93001361-115a8800-f561-11ea-9c1e-88a3b46fdfb5.png)

Thanks!

**Comment by zimmmz** [comment]
@domsterthebot hii actl idk if this helps but i got an error related to the BookingStub but not the exact same one as yours. For mine the problem is because for the compareTo() method i did not return a int and set the return type to int. sry if it didn't help. 
 
p.s. actl when you want to test your files you can just use eg. jshell *.java -q <test3.jsh in your working directory so in a way u don't need to type so many file names haha cause I saw from your ss there are like alot of java files typed out.

**Comment by domlimm** [comment]
hey @zimmmz ! no worries! appreciate it! i checked my `compareTo()` method does return an int, and also have the `@Override` keyword. so i guess that's fine!

good point!! i tried it and got a bunch of errors, so that's quite odd (likely due to the precedence of the files).. did you?

nevertheless, thanks @zimmmz !!!

**Comment by zimmmz** [comment]
@domsterthebot actually for my compareTo() method I didn't have the @Override keyword and it is fine on CodeCrunch. Ohh for me I didn't get errors when using that cmd line.

**Comment by domlimm** [comment]
@zimmmz that command doesn't work for me HAHA, but good point for that part though! ugh i can't move on...

**Comment by zimmmz** [comment]
@domsterthebot actl do you want to try remove the override keyword cause when I googled about stub just now is like an extra kind of thing. I think since compareTo() is kind of like a java method so when you override it tries to find for a class BookingStub() which is something that you don't have?

**Comment by domlimm** [comment]
EDIT: Still getting the same output in codecrunch!

For context for others:
```
public class Booking implements Comparable<Booking> { 
    public int compareTo(Booking booking) { ... }
}
```

Maybe there's something wrong with this code snippet

@zimmmz trying that now! thanks! i think you're right.

**Comment by zimmmz** [comment]
@domsterthebot hope it works for your case. actl I also not very sure and do try the codes in CodeCrunch cause for me even when I run on jshell the output is right but in the end I will still get errors in CodeCrunch.

**Comment by zimmmz** [comment]
@domsterthebot maybe you try remove the implements Comparable &lt;Booking&gt; part does it help? Cause from what I see is that Comparable interface is mainly used to sort the arrays/list since Booking is not a list therefore it cause the error = cannot find variable list?

info on Comparable = https://beginnersbook.com/2017/08/comparable-interface-in-java-with-example/

**Comment by domlimm** [comment]
@zimmmz yes i've tried to remove `implements Comparable<Booking>` and made my compareTo a regular method. 

i still get the same error! oh my...
![image](https://user-images.githubusercontent.com/46486515/93009441-cddd3980-f5b3-11ea-8baa-8c45b77d0638.png)

**Comment by marcuspeh** [comment]
It might be the class names of your other java abstract class/interface that the BookingStub inherits from. It might be different from what they want

**Comment by domlimm** [comment]
@marcuspeh hey marcus, did you have a BookingStub class implemented?

**Comment by marcuspeh** [comment]
@domsterthebot Nope but I was talking about the naming of abstract class. My friend fixed his cuz his Driver.java was named as Car.java. Once he swapped it, it solved that error

**Comment by domlimm** [comment]
@marcuspeh looks like you fixed my issue! my abstract class was named Car.java too. it works now. i passed test3 on cc. thanks a bunch!!!
@zimmmz thank you too!
