### ISSUE TITLE
Referencing and equality

### ISSUE THREAD

**Issue by FergusMok** [nus-cs2030/2021-s1#554]
I don't quite understand the answer. 
Can somebody give an example when x == y returns false? 

![image](https://user-images.githubusercontent.com/10182564/100539122-1d580b00-326f-11eb-83d0-93573da0dfe2.png)

**Comment by Octanis0** [comment]
If the value of i is between -128 and 127, the ``==`` operation will give the correct answer. Beyond this range, the operation will only compare the object reference value and not the value of the data stored in the ``Integer``.

Refer to this [StackOverflow question](https://stackoverflow.com/questions/3637936/java-integer-equals-vs#:~:text=equals%20is%20overridden%20to%20provide,to%20an%20object%20reference%20comparison.&text=%22%3D%3D%22%20always%20compare%20the%20memory,method%20always%20compare%20the%20values.&text=Integer%20uses%20Integer%20cache%20to,from%20%2D128%20to%20%2B127.)

**Comment by kaiyang96** [comment]
This is caused by something called Integer cache. Link below explains and elaborates pretty well on it.
https://dzone.com/articles/the-internal-cache-of-integers

**Comment by FergusMok** [comment]
Thanks guys. I didn't know about this. But after reading the articles, won't all the more it be true all the time?
When you x == y, you will always be referencing i == i, and comparing the reference location, and it will always be same, regardless of the Internal Integer cache or not. 

Example 1 : -128 < Integer i < 127
Integer i = 100; Integer x = i; Integer y = i;
i points directly to the memory location of int 100. x and y points to memory location of 100.

Example 2 : Integer i outside of those bounds
Integer i = 2000; Integer x = i; Integer y = i;
i points to one of the many memory locations of int 2000. x and y points to this exact location too.

I am still quite confused

**Comment by kaiyang96** [comment]
In this question, i is of type int not Integer. So when the line `Integer x = i` is called, there is auto-boxing, where java pretty much does `Integer x = Integer.valueOf(i)` for you behind the scenes. So once i is i < -127 or i > 127, the two Integer types x and y will start referencing different objects.

If i is of type Integer, then it should work as you explained.

**Comment by Octanis0** [comment]
The Integer cache means that upon initialisation, an array of Integers of size 256 will be created automatically for you. When you try to create an Integer that is within this range, instead of creating a new object, java sets your variable to point to the Integer in the array that also contains that value. This is why ``x==y`` is true for this case, since they are literally pointing to the exact same object.

When you deal with values of i beyond that range, java is creating new instances of Integer, the internal value of which is i. Every new instance of an object is assigned to an empty memory location, so ``Integer x`` will point to one Integer instance in memory, and ``Integer y`` will point to a different Integer instance in memory. Comparing them with ``x==y`` means comparing the memory locations, which will then yield false.

As kaiyang has reminded, i is a primitive int, not an Integer object.

**Comment by FergusMok** [comment]
Thanks alot @kaiyang96 @Octanis0, I missed out on the int part.
