### ISSUE TITLE
1920Sem2 Q5 Anonymous Class

### ISSUE THREAD

**Issue by wongpengyu** [nus-cs2030/2021-s1#560]
Hi, I am still seriously confused about Anonymous Class. I thought Lambdas are Anonymous Classes but they are Anonymous Functions instead. I tried googling but I got more confused.

Can someone help me out for this question? I'm not even sure how to start but I'm thinking I'm supposed to write a whole class without declaring it.
Thanks in advance.

![image](https://user-images.githubusercontent.com/72071732/100543653-50f55e00-328c-11eb-85e3-479381723cdd.png)

**Comment by banchiang** [comment]
This was mentioned in the first part of the catch up session.
https://github.com/nus-cs2030/2021-s1/issues/546#issue-752849335

Also in the Functional Interface lecture slides 10-12 there are mentions of the anonymous class as well.

**Comment by Henry-Yuan-He** [comment]
Anonymous class is a class without a name, since we may only use it only once.

If we want to create a new class that implements an interface with abstract methods but can initialize an object, we must override all abstract methods in the interface. Now, only overriding the methods but too lazy to give a class a name is how we write an anonymous class.

<img width="1031" alt="屏幕快照 2020-11-29 下午10 06 11" src="https://user-images.githubusercontent.com/55197157/100544214-1c36d600-328f-11eb-95d1-aff7144fbecf.png">
