### ISSUE TITLE
Quick qn on Pure Functions

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#565]
Hi all,

Is this a pure function? It says that it has to return the same input, does it mean type or the value?

```java
int increment(int i) {
     return i + 1;
}
```

**Comment by fans2619** [comment]
It should return same output every time you give it same input. So I think this is a pure function.

**Comment by joannecya** [comment]
yea since the output is fully determined by the input, this should be a pure function

**Comment by naranghardik16** [comment]
The following points need to be kept in mind while considering the definition of a pure function.

- Given the same input, will always return the same output.

- Produces no side effects.

- Relies on no external state.

Since the function increment follows the above mentioned points, it is a pure function.

**Comment by kohkenneth** [comment]
Hi! maybe you can take a look at issue #556 there was a bit of discussion regarding pure functions as well! All the best for finals!
