### ISSUE TITLE
Questions about project 1

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#69]
Can I ask is the serverList that we created suppose to be mutable to reflect the changes as each event calls execute?
This means that each event has access to the one serverList and depending on the state of the serverList, it acts accordingly.
Is this the correct approach to tackle this poject ? Please help me out as i am very confused about this project thank you!

**Comment by marcuspeh** [comment]
Quite curious about this too. Its the only way i can think of to solve lvl 4 of the project.

**Comment by SkyBlaise99** [comment]
I used that approach and passed all the test cases. So I guess you can do it unless the prof says otherwise and change the test case someday

**Comment by kaiyang96** [comment]
I think the 'immutability' of the serverList they want us to use is so that we cannot assign a whole new instance of List to serverList. However, the editing of server status within the first instance of serverList seems like the correct approach to the problem.
Good luck on your progress for the project!

**Comment by leeleonard98** [comment]
Yes, i do think that although servers are immutable, the server list can be mutable so in this case what you can do is return a new server when the server is serving someone, thereafter change this server state from the list of servers.
