### ISSUE TITLE
Why is Predicate<? super T> used in Lab 4

### ISSUE THREAD

**Issue by charoi** [nus-cs2030/2021-s1#74]
# Description 
Hi! For lab 4 bonus question, I need help understanding generics in ?
Why is a wildcard used here? I initially tried Predicate<T> pred in my parameter for the filter function... and I thought it was fine. After tinkering around I did get <? super T> but wanted to ask why is this preferred? Why is it not <? extends T> 
Thanks.

## Topic: 
Generics

**Comment by domlimm** [comment]
A wildcard has to be used because [Predicate](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/function/Predicate.html) requires an input of generic type.

I think extending T will only inherit whatever attributes, properties inside T, whereas a super of T will completely look up and down the hierarchy of the data(?) type. That's my understanding... 

Appreciate if others can add on too. I think my understanding on this is rather weak too lol

**Comment by SkullPirateTK** [comment]
Using the example from the lectures, `<? extends T>` in the predicate will not work correctly as you can put in a `Predicate<CheeseBurger>` into a function that compares burgers, and `Burger` may not have the properties required. However, `<? super T>` is guaranteed to work as the `T` will have the properies from its super class, e.g. `Predicate<Burger>` can be used to compare cheeseburgers.

**Comment by chongweil907** [comment]
From my own understanding is that Predicate is testing whether an object has the following attributes. A super class of that object will definitely have those attributes since we are extending from it.  This is why we use <? super T> instead. What we are testing on this current object, we can also test it on it's super classes.

**Comment by kaiyang96** [comment]
Let's say we have A which is a parent class of B, and B is the parent class of C, so A > B > C. 
Focus your attention to class B. We can freely replace all instances of A with B because by LSP you expect the 'child' to perform exactly like the 'parent'. However, you cannot replace all instances of C with B because class C might have extra methods, parameters that class B might not. Therefore, for predicates we use <? super T>  as we want to accept everything that is a 'parent' of T.

**Comment by darrenhoon** [comment]
1. Suppose we did <? extends T>
2. This implies that the parameter type can be the child class of the ImmutableList class
3. If we were to use an extreme example of the ImmutableList being Object class, then the Predicate which takes in an Integer class is a child of the Object class (as are all classes in fact, since the Object class is the root class)
4. But we know that the Integer class will have properties that the Object class do not have (eg the Integer class may have a private final int = x), where the Predicate will act on these additional attributes of the child class
5. This leads to an error when those additional attributes are evaluated against the Object class, which does not have the required attribute, thus an error

At least that is the logical way to think about it. which is why only <? super T> works since you want your Predicate to work for all instances, and they only way to encompass all instances is to account for attributes that all classes will have. You cannot be certain that ? will have the attributes of T if ? is a child of T, but you can be certain that ? has the attributes that T has if ? is a parent of T (since T is the one with more attributes in addition to the ?)
