### ISSUE TITLE
[PROJECT] Failing test cases repeatedly

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#91]
Hi guys, I would like to ask on where you updated the servers list? I did mine in ServeEvent (returns DoneEvent) & WaitEvent (returns ServeEvent),  both classes return the updated servers list. I feel like I'm beating around the bush...

It's odd, for the 4th test case, `sim4_1 sim4_2 sim4_3 ...` I'm stuck with sim4_3.

I debugged, amended my codes, etc. Tested out the test cases we were given for Level 4 and found that I'm actually not getting the expected results locally, but it all passed in CC. So, I went onto CC and downloaded the latest submission files (at which i failed to pass sim4_3). Re-ran locally and same thing failed for Level 4 test cases (the 3 given to us). Odd...

Any pointers? Been debugging for 4 days... Like straight.

Thanks y'all! 😭 

![image](https://user-images.githubusercontent.com/46486515/94187573-b1f26580-feda-11ea-9c97-985210bd6f54.png)

**Comment by lkldev** [comment]
Hi, since the server that is serving the customer is decided in arriveEvent, you might want to check if you are passing in the updated server list when you call the subsequent arriveEvent. Even though your ServeEvent and WaitEvent return the updated server list, chances are the server that is appointed to the customer at arriveEvent is not updated as you are referencing a different list.  Once you reference a different list, the server will not be updated correctly subsequently. So instead of replacing the list, you might want to think about replacing the server instead.

**Comment by zzkzzzz** [comment]
What I do is that I updated my server list after executing an event only on that particular server in the list. Then pass the updated server list to the next event in the queue. The other important thing is the event comparator, definitely,  need to compare the start time of the event. What if the start time of the two events is the same? then need to compare the customer id. Hope this helps.

**Comment by aaron-ljx** [comment]
I created a separate class that takes in a list of customer and a server list.  I update the server list in that class. The idea is that every customer should be able to know what is the current state of the server list since whether the next customer will be served or not for example would be determined by the previous customer. Afterwards, I pass in the updated server list into the ArriveEvent class (which is then passed into the EventQueue) and the ArriveEvent class will return different events based on the updated server list that was passed in.

**Comment by domlimm** [comment]
Sorry for the late reply, decided to take a day off from this and catch up on what I haven't done 😭
Thank you for all of your constructive inputs! Really appreciate them!
@lkldev @zzkzzzz @aaron-ljx
